### ISSUE TITLE
String inspector acts oddly on inspect

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#106]
If you have a string inspector, e.g. inspect 'hello', and use the Jade menu item inspect, it gives you an dialog titled
    Note
    Sorry, we are not yet prepared to convert 'hello' to an OOP!

(And I had to type this in - copy did not work on the dialog) (frowny face) 

And also you get a dialog
     Executing GemStone/Smalltalk Code... 
on hello that never goes away.

If you close it and close the Note, now you get yet another dialog (a copy-able one) 
    Invalid arg 2: Cannot coerce a GciSession to OopType64

and fourthly... it opens an inspector on nil.

All in all, this is a minor issue... but not handled very gracefully.

**Comment by ericwinger** [comment]
There was a dialog deep within the GciSession class which threw up a MessageBox if the context object could not be converted to a known oop type. I changed the dialog to an error and I moved that error outside the timing loop which should help prevent the timing box appearing along side of a dialog and giving the user grief. 

Also wrapped the actual inspect to give a better message. Fixed in 3.0.19.

**Comment by LisaAlmarode** [comment]
To clarify the new behavior: There are four Jade menu items on a string inspector; inspect, display, execute, and file in.  
The inspect response is a Note with a preamble to the apology (preferred)
The display and execute responses are Jadeite Errors with the apology (okay, can be copied)
The filein... still has issues.  Which are covered under new issue #118 and existing issue #70.
So allowing for those separate bugs, I'm content with the behavior.
