### ISSUE TITLE
Oscar-3.0.40: `browse object class` menu item in inspector (debugger) opens dictionary browser...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#192]
Should open a project browser (I think) if the class is packaged ...

**Comment by dalehenrich** [comment]
method browser also opens a Dictionary browser ..

**Comment by ericwinger** [comment]
Method browser and inspector should both open a projects browser if it is a rowan-ized package and a dictionary browser if not. Fixed in 3.0.46

**Comment by LisaAlmarode** [comment]
Not sure what inspector this might be fixed in.  Works well from method list browsers

Highlight RwClassDefinition and do inspect-it.  (notice the menu par says "Jade" and should say "Jadeite").
In the resulting inspector, use menu item Jade > Browse class.

( 1 ) It opens the project browser but does not select the class.
THEN it ALSO opens the Dictionaries browser which does select the class.

( 2 ) In a debugger, with RcClassDefinition as the receiver int he upper right pane, do "browse object class".  See a dictionaries browser (only the one).

**Comment by ericwinger** [comment]
The inspector wasn't working when the inspected object was a class. Instances of classes worked fine. Fixed that in the inspector. 

Debugger variable pane was using old-style find class which was replaced.

Fixes in 3.0.47.
