### ISSUE TITLE
MethodListBrowser needs the token in the title bar

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#209]
If you do a senders search on a method that has no senders (e.g. RwProjectDefinition newForGitPackageProjectNamed:), the MethodListBrowser provides no clue as to what was searched on. Normally I'd expect to find that trailing off along in the title bar.

**Comment by ericwinger** [comment]
@LisaAlmarode  - Since title bars were contentious earlier (#22 ), let me make a proposal for your consideration. 

Current window title:
``<window name> for <user id> on <stone name> [session number] with remote gem on <gem host>``

That makes the method list browser title look like this - 
![image](https://user-images.githubusercontent.com/36212516/46426443-7e1d4480-c6f3-11e8-9784-18e63a1eaf81.png)

Proposal: 
``<Senders/Implementors> of <search string> for <user id> on <stone name> [session number] with remote gem on <gem host>``

The down side is that the "for <user id>..." will get pushed around and the eye won't see a common pattern. The upside is that you know quickly what you searched on. 

Alternatively, we could put the search string on the far right (if I interpret your suggestion correctly) but that would often get cutoff and the window label pattern would not match other browsers. 

Thoughts?

**Comment by LisaAlmarode** [comment]
I assert that the search string is an integral part of the title, not incidental data.  So, I like <Senders/Implementors> of <search string> for <user id> on <stone name> [session number] with remote gem on <gem host>

**Comment by dalehenrich** [comment]
putting the search string in quotes (I'm a fan of using printString in labels), would make the searchString begin and end points very obvious

**Comment by ericwinger** [comment]
Fix will be in 3.0.42. 

@LisaAlmarode  Might want to scan around for the different places senders/implementers are sent. I think I fixed them all but my refactoring was big enough (and test coverage may not be complete enough) such that I missed a couple spots.
