### ISSUE TITLE
Project List write... gets no project found

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#21]
When you use the project list browser menu item write... , yu get a walkback.
This is with Oscar 3.0.3 and Rowan df3c407, reloaded but not rebuilt.

This reproduces with rowan projects, e.g. select Tonel (even though there are no changes), and try to write that out.  

a UserDefinedError occurred (error 2318), reason:halt, No loaded project named nil found

UserDefinedError (AbstractException) >> _signalWith: @5 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwGsImage class (Object) >> error: @6 line 7
[] in  ExecBlock0 (RwGsImage class) >> loadedProjectNamed: @5 line 5
[] in  ExecBlock0 (RwGsImage class) >> loadedProjectNamed:ifAbsent: @12 line 13
StringKeyValueDictionary >> at:ifAbsent: @6 line 8
RwGsImage class >> loadedProjectNamed:ifAbsent: @5 line 8
RwGsImage class >> loadedProjectNamed: @2 line 4
RwPrjWriteTool >> writeProjectNamed: @3 line 4
RowanProjectService >> write @4 line 2
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
@LisaAlmarode 

This broke because I removed the old way to do service updates. If you see any stacks with a service object referencing the inst var ``transport`` it's the same type of bug.  

Perhaps you can just collect these and make an omnibus bug? 

If it's too hard to distinguish then please just file individual issues. Thanks.

**Comment by LisaAlmarode** [comment]
Verified that write changes menu item works in 3.0.6... other project list issues under #23.
