### ISSUE TITLE
method list in method browser reorders on accept 

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#216]
Probably need to sort on class & selector to keep list ordered.

**Comment by ericwinger** [comment]
@dalehenrich  After saving methods in a method list, I don't see the list of methods get reordered. 

I created the scenario in the picture below.  I tried saving a method with the method list fully displayed, partially displayed, and covered up. I also tried different packages in the mix. 

Unfortunately, the list reorder didn't reproduce. Any suggestions on a better reproduction case? Or maybe I didn't understand the nature of the bug? 

![image](https://user-images.githubusercontent.com/36212516/46559380-0db62500-c8a5-11e8-9823-55f0e925e128.png)

**Comment by ericwinger** [comment]
Assigning to @dalehenrich  for guidance.

**Comment by dalehenrich** [comment]
It happened to me a month ago while I was working on a fairly large list of implementors, but I don't recall the exact selector I was using ... I have probably recognized that the reordering was happening less than a half dozen times in the 9 months I have been using Jadeite ... 

Have you looked at the algorithm for clues as to what might be triggering a reordering? I recall that the reordering happened on accept of a change in the method ... and that's about it ...

Oh I seem to recall that it happens when the list is larger than the amount allocated for the method list ... don't recall if it ever happened to a small list ... 

... another tidbit is that it seems that there were several methods from the same class so perhaps it was a senders browser ... I recall that when I saved the method in the large list that the saved method was moved to be later in the list so it's almost certainly a senders browser ... the order of the methods in the same class was not being preserved ..

**Comment by dalehenrich** [comment]
... I don't recall if it happened every time ... i noticed the issue after i had edited at lest one or two "pages" of methods, because when I noticed what was going on I  had to go back and look at all of the methods that were in the list and the reordering of methods within a class is what I distinctly remember ... but it is possible that it didn't happen on every edit (of course I may not have edited every method) ... now I'm about drained dry of details:)

**Comment by ericwinger** [comment]
Think I found it. It was using the old Jade method list, but only if you did senders from a debugger source pane. 

You may have hit it more often in the past because in the intervening time the method list browser calls were consolidated to always open the Jadeite method list. Or, most of them. There may be some lurking. 

See #220 for check of other places the old Jade method list was used. 

There will be a fix in Oscar 3.0.41.

**Comment by LisaAlmarode** [comment]
I don't reproduce a problem; this isn't very definite but Dale will notice if it does show up.

**Comment by dalehenrich** [comment]
reopening as it just reproduced for me in 3.0.53 ... in this case it might have been a commit that caused the list to reorder ... not sure I was in the middle of a big set of changes (and had just lost a bunch of work because of a crash), so I can't tell exactly what lead to this ... big list of senders and reorerding did not seem to be happening ... I did a commit and the list was definitely reordered ...

**Comment by ericwinger** [comment]
Reassigning to @dalehenrich and @LisaAlmarode for a reproduction case.

**Comment by ericwinger** [comment]
Reassinging to myself. Need to check the sort headers functionality  in the method list. Possibly related to #384.

**Comment by ericwinger** [comment]
Hmm, the sort headers appear to be setup properly. @LisaAlmarode  - it might be reproducable by focusing on post-commit behavior.

**Comment by LisaAlmarode** [comment]
If this reproduces, I'd need more detail: particularly, if there are added/removed/moved methods, and the initial and after commit order (one or the other is either badly ordered, or sorted using a different criteria).  Also, the specific number of senders/implementors wpi;d be helpful, or at least a numeric estimate ("pages" is too vague - how big is the window?). The initially opened browsers don't indicate the sort order, and if you fiddle with sort order you can get secondary sorts without indicators.
