### ISSUE TITLE
Ctl-B does not `debug` selected test in SUnit browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#218]

**Comment by ericwinger** [comment]
Fixed in 3.0.46

**Comment by LisaAlmarode** [comment]
Control-B does debug-it in SUnit browser.  Reopening since the Console does NOT debug-it on control-B, it opens a dictionaries browser.  The popup menu item does claim to but the actual keystokes not so much.

**Comment by ericwinger** [comment]
I've got a fix in 3.0.47 for review.

**Comment by ericwinger** [comment]
Also @LisaAlmarode see https://github.com/GemTalk/Jadeite/issues/243#issuecomment-438493471

**Comment by LisaAlmarode** [comment]
If you are in the ProjectBrower, in a test class, and go to the Sunit tab and click control-B, you get
an error dialog:
JadeiteSUnitInClassPresenter does not understand #jadeDebug

Everything else that ought to work, appears to work. 

I think the Method List Browser handling could use examination - you can't do a control-B, and the Run Tests menu item is plural but I suspect only runs the one test. The text pane has other execute-its, but no debug-it.

**Comment by LisaAlmarode** [comment]
See new issue  #280 for the method list browser parts of this issue.

**Comment by ericwinger** [comment]
Partial fix in 3.0.49 to fix Ctrl-B walkback.

**Comment by LisaAlmarode** [comment]
I think a test that has run "debug" (with no walkback) should display with a check box.  This may be intended API, but I'm reporting that I'd like to see the control-B, popup menu item debug, or the button on the right with the browser-with-traffic-light icon, make the test that was run change the display from the envelope to the check mark. 

Also, other popup menu items and control keys equivalents labeled on the popup menu are incorrect or broken:

 - I get MNU from the SUnit tab right click menu item runAndMeasureTime.  The right button with the fuzzy clock does work correctly.

 - The menu items Run All and Run Selected claim to match control-S or control-A, but I get JadeiteSUnitInClassPresenter does not understand #editSave/#editSelectAll.

**Comment by ericwinger** [comment]
Have fixes for these in #218. Debugged tests that passed show a green check in both sunit browsers. If a group of tests methods was selected, the first N that pass will show green checks until the N+1 that fails or errors. Then a debugger will be shown as normal. 

MNU measuring time fixed. 
Ctrl-S & Ctrl-A removed, but Ctrl-A secretly selects all the tests which is intuitive and might actually be handy. 

Fixes in 3.0.52

**Comment by LisaAlmarode** [comment]
All the reported problems are good now - I like this behavior.  Of course being Lisa I have a couple of more quibbles.

- while you have control-A to select all in the project browser Sunit tab, control-A runs all in the Sunit browser.   It's best to keep these two similar features' behavior as close as possible.

- Along this line, the Sunit tab menu item refresh and the Sunit browser menu item reset should use the same term.  I think reset is the preferred term.  By me, anyway.

- the Sunit browser middle class pane does not have a run tests menu pick.  This is better than it passing tests incorrectly as with issue #341 but it seems handy.  Especially since control-A does not select all.

- If I'm in the method list pane of the project brower, and I select a non-test methos (with a selector that does not  start with 'test') and control-B, it brings me to the Sunit tab with all the tests showing envelopes and the footer green saying "1 run 1 passed 0 failures 0 errors".  This does not seem like correct behavior although it's fairly harmless.

**Comment by ericwinger** [comment]
Fixed in 3.0.73. 

Believe I got all the quibbles cleaned up. Note Ctrl-A selects the list of test classes or test methods in the sunit browser depending on cursor focus. This matches Ctrl-A behavior in the sunit tab. Run All tests & Run Selected are now Ctrl-Shift-A and Ctrl-Shift-S respectively. Both Ctrl-Shift-A & S are available from the Classes pane in the projects browser as menu picks, too. 

Enablement of test method selection in project browser reflects type of method being selected, too.

**Comment by LisaAlmarode** [comment]
In the projects browser, control-shift-A is on the methods pop-up and drop-down menus.  It ought to be on the classes menu since it applies to the class, not a specific method.   This may be a matter of taste; I looked for it for in the class pane.

There's no menu item on the classes pane popup menu in the SUnit browser, but there's the run icon so I think this is fine.

------------------

My last quibble has the same behavior in v3.0.74: 

If I'm in the method list pane of the project brower, and I select a non-test method (with a selector that does not start with 'test') and control-B, it brings me to the Sunit tab with all the tests showing envelopes and the footer green saying "1 run 1 passed 0 failures 0 errors". This does not seem like correct behavior (and in fact, the control-B menu item is grayed out on the method menu).  But it's fairly harmless so you don't really need to address this.

-------------

I'm reopening but these are rather minor complaints.

**Comment by ericwinger** [comment]
> In the projects browser, control-shift-A is on the methods pop-up and drop-down menus. It ought to be on the classes menu since it applies to the class, not a specific method. This may be a matter of taste; I looked for it for in the class pane.
> 
> There's no menu item on the classes pane popup menu in the SUnit browser, but there's the run icon so I think this is fine.

Ctrl-Shift-A runs all the tests in the selected class. It's like the Ctrl-Shift-A in the projects browser sunit tab. You're looking at a list of methods and you want to run them all. So I'm inclined to leave the menu option on the method pop-up to be consistent.

**Comment by ericwinger** [comment]
Changed the behavior of Ctrl-B so that only the selected test methods get run. If you choose a method that is not a test method, it will take you to the SUnit tab but show 0 tests run. Combinations of test & non-test methods are handled, too. Checked for  3.0.75.

**Comment by LisaAlmarode** [comment]
While I don't think perfection has been achieved, it's reasonable.  Will defer further complaints.
