### ISSUE TITLE
Fix project menus

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#23]
I recently broke the project menu items. Need to fix.

**Comment by ericwinger** [comment]
Several improvements were made as of Oscar 3.0.5. Asked Lisa for help identifying remaining broken project menu items.

**Comment by LisaAlmarode** [comment]
(1) Pull from Git gets a walkback.  I think it might be doing a push.

UserDefinedError (AbstractException) >> _signalWith: @5 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwGitTool (Object) >> error: @6 line 7
[] in  ExecBlock1 (RwGitTool) >> performOnServer:logging: @24 line 21
RwGitTool >> performOnServer:status: @4 line 4
RwGitTool >> performOnServer:logging: @2 line 4
RwGitTool >> performGitCommand:in:worktree:with:logging: @13 line 9
RwGitTool >> performGitCommand:in:with: @2 line 4
RwGitTool >> gitpushIn:with: @2 line 3
RwGitTool >> gitpushIn:remote:branch: @4 line 3
RowanProjectService >> pushToGit @8 line 6
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @9 line 11
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by LisaAlmarode** [comment]
The project list menu items tested in 3.0.6:
Make default, clone, load, changes, write, commit and refresh work okay.
(Changes takes an unreasonably long time for a package with no changes)
push and pull probably are okay... I get errors with my test repository since I don't have an origin, and the error messages are frightful, but this can be deferred. 

There are problems with show packages, checkout, log, and inspect

(1) Show packages gets a walkback:

a ArgumentError occurred (error 2283), reason:rtErrInvalidArgClass, nil is not one of the class kinds in anArray( AbstractCharacter, CharacterCollection).
ArgumentError (AbstractException) >> _signalWith: @5 line 25
ArgumentError (AbstractException) >> signal @2 line 47
UndefinedObject (Object) >> _error:args: @15 line 11
UndefinedObject (Object) >> _validateClasses: @10 line 9
String >> , @30 line 55
RowanProjectService >> packageNameString @5 line 7
GsNMethod class >> _gsReturnToC @1 line 1


(3)  Checkout gets a weird error.  I created a local branch on the command line (git branch lisa) and then tried to checkout in oscar. 

a MessageNotUnderstood occurred (error 2013), reason:rtErrCantPerform, a UndefinedObject does not understand  aRowanProjectService
MessageNotUnderstood >> defaultAction @2 line 3
MessageNotUnderstood (AbstractException) >> _signalWith: @5 line 25
MessageNotUnderstood (AbstractException) >> signal @2 line 47
RowanProjectService (Object) >> _error:args: @15 line 11
RowanProjectService (Object) >> cantPerform:withArguments: @8 line 9
RowanProjectService (Object) >> _perform:env:withArguments: @7 line 24
RowanProjectService (Object) >> perform:withArguments: @4 line 16
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @9 line 11
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1


(3)  inspect gets error: RowanProjectService does not understand #inspect.

(4)  log is broken (gets error: no loaded project named nil found)

**Comment by ericwinger** [comment]
Please recheck this in Oscar 3.0.7. Think I got everything fixed but there may be more menu issues lurking.

**Comment by LisaAlmarode** [comment]
In 3.0.7, slightly hybrid due to new release process, with latest Rowan oscar branch:

show packages - menu item removed - OK
checkout - works!  - OK
log - slightly worse: this now gets 'Compiler class does not understand #isAValidIdentifierChar: and a SmalltalkWorkspace window becomes visible.
inspect - no change, still errors: RowanProjectService does not understand #inspect.

**Comment by ericwinger** [comment]
inspect remove - Dolphin strips out all the development code out of the deployed image, including inspectors. Retaining the development code opens up an entirely new can of worms.

**Comment by ericwinger** [comment]
Log view will be fixed in 3.0.9

**Comment by LisaAlmarode** [comment]
Reassign to me when I am able to review

**Comment by ericwinger** [comment]
Added vertical scroll bar.
