### ISSUE TITLE
workspace could use a `browse projects` menu item ... (3.0.45)

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#265]

**Comment by ericwinger** [comment]
Replaced Browse Classes which opened a dictionary browser (going away) with a Browse Projects. Fixed in 3.046.

**Comment by LisaAlmarode** [comment]
In a loose workspace, it seems like you'd want more than just the Project Browser.  Also, the location under menu bar items might better to be more consistent with the Console,  So I would recommend adding a "Browse" menu bar item rather than putting it under the jadeite menu.  But I'm not sure we've carefully thought through what is "Jadeite" vs other menu categorizations so it may be okay to defer until we think it through?
