### ISSUE TITLE
(3.0.50) CTL-S is not properly bound in method list browser from list references

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#297]
Not expected:
![image](https://user-images.githubusercontent.com/623951/48666714-f3629000-ea7b-11e8-81c6-7ad377ad2db9.png)

**Comment by dalehenrich** [comment]
CTL-F is not bound eitther ... looks like all of the bindings are lost?

**Comment by ericwinger** [comment]
Should be fixed in 3.0.51. The accelerator keys are not at all straightforward in Dolphin. Removal of a high-level menu recently removed the ctrl bindings even though the bindings were specified in the presenter. 

I've  looked into writing tests that simulate the ctrl keys so they don't get lost in the future, but so far successful tests have eluded me. Will continue to try.

**Comment by LisaAlmarode** [comment]
Only verified these two in 3.0.51 so
