### ISSUE TITLE
 UndefinedObject does not understand  #'comment' Failure shifting to Dictionary browser.

### ISSUE THREAD

**Issue by alexkogan** [ericwinger/Jade#326]
added inst var in project browser to new class. Shifted view to Dictionary brower. Got error on refresh.

```
a MessageNotUnderstood occurred (error 2010), a UndefinedObject does not understand  #'comment'
RowanClassService >> basicRefreshFrom: @4 line 5
RowanClassService >> refreshFrom: @2 line 3
RowanClassService >> updateClass @4 line 5
RowanClassService >> update @2 line 3
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @6 line 11
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1
```

**Comment by dalehenrich** [comment]
this is/was error in RowanServices ...

**Comment by LisaAlmarode** [comment]
This does not seem to be happening in Jadeite/Rowan oscar 3.0.50, unless there's something missing in reproduction details.  There's isn't a refresh button in dictionaries browser; tested by click away and back.   Clicking away and back takes forever which may be a new problem.
Since this was reported so long ago we can hope it has healed... so closing.
