### ISSUE TITLE
Need service transport diagnostic feature

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#349]
When diagnosing Jadeite bugs it would be nice to have call tracing like GBS. Probably the most straight forward would be a switch that enabled logging to separate files on both the client and server with a unique serial number to identify "transactions." 

Better yet, we could log server and client files to one client file but that could run into interleaved writes on the client if one isn't careful. 

See client methods ``BrowserUpdate>>basicIssueCommand:session:`` and server method ``RowanCommandResult class>>addResult:`` as possible logging hooks.

**Comment by LisaAlmarode** [comment]
It turns out that we already have built-in a GCI call tracing feature, which does part of the GBS call tracing.  See the Jadeite login Advanced tab, "Debug GCI" button.  

This writes the client GCI calls to a file on the client.  It does not report the details of the calls, just the GCI call and bytes sent/received.  Alas! no timestamps.

I think it might not be very solid; I had two sessions and I think it opened a second log file but it wedged hard when I tried the OOM test.

**Comment by ericwinger** [comment]
I'm going to call this complete. One can turn on ``Logging`` in the transcript, then ``Browse Jadeite Logs``.
