### ISSUE TITLE
(3.0.52) drag/drop of instance method ends up on class side

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#354]
Pre drag drop screenshot:
![image](https://user-images.githubusercontent.com/623951/49767209-78605400-fc8c-11e8-8884-ca58268cd4e1.png)
Where'd `_persistentPreferenceDict` method go? Post drag drop screenshot (drop target RwgsPlatform):
![image](https://user-images.githubusercontent.com/623951/49767260-9f1e8a80-fc8c-11e8-8d8c-debb687ffa28.png)
It's on class side:
![image](https://user-images.githubusercontent.com/623951/49767315-d8ef9100-fc8c-11e8-96e6-ac114c8460b4.png)

**Comment by ericwinger** [comment]
@LisaAlmarode - Can you help me characterize this bug?  I tried use cases with the class methods in the example, hierarchy view & classes view, variants of the methods existing (or not). No luck.

**Comment by LisaAlmarode** [comment]
This is maddening. It looks like in the method RowanClassService>>savemethodSource:category:, the RowanClassService's #meta instance variable is unreliable and becomes nil as the side effect of some other operation.  It would be nice if modifications to instance variables such as meta use the accessor meta: rather than there being side effects, following proper standards like that make debugging much easier.

A similar problem is easier to reproduce on the class side (although not completely reliable)  Try creating a new class method, clicking on a different package and back to the package and class of the added method, then dragging the class method to a subclass.  meta is usually nil which results in an instance method getting created. 

For the instance side, I've been able to reproduce by going to the class side and doing things like removing class methods or displaying senders, which has some side effect on the RowanClassService, and then going to the instance side and dragging a method to a super class or subclass.

**Comment by ericwinger** [comment]
Have a fix to try in 3.0.53. We weren't setting meta properly before method compile. 
See ``JadeiteProjectsBrowserPresenter>>onDropOnClassList:``

**Comment by LisaAlmarode** [comment]
I don't think I can reproduce it.  Hard to be sure...
