### ISSUE TITLE
(3.0.53) "a InternalError occurred (error 2727), reason:nativeStackNotConvertableToInterpreted, OffsetError: object does not have varying instVars" from debugger

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#367]
Same debugger instance after getting [index out of bounds error](https://github.com/GemTalk/Jadeite/issues/362#issuecomment-448799006):
![image](https://user-images.githubusercontent.com/623951/50255935-e6053200-03a8-11e9-9cdf-5e11769deadc.png)
This error occurred after trying to use the `restart` button ... after hitting Issue #362 ... so it may or may not be related:
```
a InternalError occurred (error 2727), reason:nativeStackNotConvertableToInterpreted, OffsetError: object does not have varying instVars
InternalError (AbstractException) >> _signalWith: @5 line 25
InternalError (AbstractException) >> signal @2 line 47
[] in  ExecBlock1 (GsProcess) >> _convertToPortableStack @6 line 34
OffsetError (AbstractException) >> _executeHandler: @3 line 8
OffsetError (AbstractException) >> _signalWith: @1 line 1
OffsetError (AbstractException) >> signal @2 line 47
UndefinedObject (Object) >> _errorNotIndexable @7 line 6
UndefinedObject (Object) >> at: @5 line 13
[] in  ExecBlock0 (GsProcess) >> _convertToPortableStack @15 line 16
ExecBlock0 (ExecBlock) >> onSynchronous:do: @2 line 14
GsProcess >> _convertToPortableStack @4 line 32
GsProcess >> _localTrimStackToLevel: @4 line 38
GsProcess >> _trimStackToLevel: @2 line 11
GsNMethod class >> _gsReturnToC @1 line 1
```

**Comment by dalehenrich** [comment]
... after reproducing the walkback ... the `Restart` button works in debugger in which #362 hadn't occurred yet ... so #362 just might be the root cause ...

**Comment by ericwinger** [comment]
Once the initial walkback in #362 was hit, Jadeite has not finished it's work and is in a bad state. Further walkbacks are not unexpected. In this issue, we are presumably trying to trim the stack to an invalid level. The invalid level is possibly because #362 prevented Jadeite from setting the trim level properly. 

The following statement is difficult to understand. Once an error occurred, I wouldn't expect ``Restart`` to work even if it visibly appeared to do so. It could have bad internal state. Were there two debuggers in play at the time of the error? 
>> ... after reproducing the walkback ... the Restart button works in debugger in which #362 hadn't occurred yet ... so #362 just might be the root cause ...

Closing. It can be reopened if #362 is fixed and still recurs.
