### ISSUE TITLE
(3.0.53) Inspector should keep associated root object alive ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#385]
This inpsector was opened from a debugger and the debugger itself was subsequently closed:
![image](https://user-images.githubusercontent.com/623951/50531093-e17ffe00-0ab9-11e9-9651-c49009e4d3db.png)
The item shown was a string originally, but over not too long of a time, the oop for the string was obviously recycled ... it shouldn't be too hard to arrange for the root object of an inspector to be put into an export set until the window is closed ... greatly reduces the utility of the inspector, when you can't count on the objects staying alive for the life of the window ...

**Comment by LisaAlmarode** [comment]
I've been trying to reproduce a problem, and I haven't reproduced the reuse that Dale reports.  

However, suggestively, I keep hanging jadeite in the attempt. Based on the report, I assume this is a single-session, not doing MFC/epoch or with reuse by another session, but just a problem within a single session's view and perhaps not even interrupted by commit or abort. 

The circumstances of my hang are that I've got it setup with a dictionary inspector that was opened out of a debugger, then the debugger was closed.  I've gone and created a bunch of objects one way and another (by loading rowan sample specs, created strings in a collection, loading my plantis code).  I'm innocently working trying to create objects and perhaps I get an MNU and terminate the debugger.  The dialog tells me that it's sending #terminate to some OOP.  After 60 seconds I lose my session.  This has occurred four times since midafternoon. Nothing shows up in jadeite.errors.

**Comment by dalehenrich** [comment]
The inspector I had was on a persistent object that was internal to a Rowan project ... the Rowan project was unloaded and then I did a series of test runs (from SUnit browser) and probably (several?) Rowan project writes (which create a lot of objects) before I came back to the inspector and saw the Strings had been replaced by methods ... so clearly I was saving methods too ... 

I've seen this losing objects behavior for forever in Jade/Jadeite and just now figured that it was worth cleaning up this bad behavior ... I think that @ericwinger has confirmed that Jade does not even try to keep inspected objects alive so we might not need explicit recreation of this bug ...

**Comment by ericwinger** [comment]
Should have a fix for the immediate problem in Oscar 3.0.57. There is now a simple registry of window handles to objects held in SessionTemps. When the inspector is opened, the window & it's root object is registered. When the window is closed the entry is removed, releasing the object.  The inspector is the only window that uses it. We can add more windows as necessary.

**Comment by LisaAlmarode** [comment]
The original issue I was able to reproduce before, doesn't seem to be showing up now.
