### ISSUE TITLE
(3.0.53) useful to be able to open method browser on selected methods in project browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#388]
recently, I've found it convenient to use the method browser to when writing and reading code ... and when I wanted to be able to "group" the following selected methods into a method browser, I found that I couldn't:
![image](https://user-images.githubusercontent.com/623951/50613339-17dec400-0e92-11e9-9a01-783c84f892a7.png)

**Comment by LisaAlmarode** [comment]
This is quite unclear! I see one selected method in the project browser.  On studying this, I think there is more than one method actually selected.  If including a screenshot it's wise to ensure that important details are visible... otherwise why bother...

I believe this request is to compose a method browser containing a deliberately/arbitrarily selected set of methods by multiple-select in the project list browser method pane.

**Comment by dalehenrich** [comment]
... Sorry about that ... the picture is meant to illustrate that **there is no menu item** for opening a method browser on selected methods ...
Contrast with the sunit browser menu item (Browse Methods):
![image](https://user-images.githubusercontent.com/623951/50660624-4ffb0b00-0f55-11e9-9ee0-aa6f5a9b6eec.png)

**Comment by ericwinger** [comment]
This was pretty straight forward. They'll be a Browse Selected Methods in the projects browse in 3.0.54.

**Comment by LisaAlmarode** [comment]
The menu item in the SUnit browser is "browse methods" not "browse selected methods".  But worn down by kermit css and ssl key generation... I am going to let this pass and not reopen this method.  Possibly I will complain later.
