### ISSUE TITLE
Selecting class in Project Browser changes test status icons in SUnit Browser

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#410]
This is the title from issue #294, but that issue has got a bit muddy. 

If you run tests in the sunit browser then go to a project browser and select that class, just select it... all the cross, check mark and triangle icons revert to the open envelope.  That's a little unfair.  

Vice versa, too... if you have run the tests in the project browser sunit pane and select the class in the sunit browser then the icons disappear in the project browser.

**Comment by LisaAlmarode** [comment]
See also issue #293, which reproduces in 5.0.56 and is similarly annoying.

**Comment by ericwinger** [comment]
The test results between a sunit browser and sunit tab should sync nicely now and not wipe the test results in the sunit browser when selecting the class in a projects browser. Fixed in 3.0.58. https://github.com/GemTalk/Jadeite/commit/15ec383aa4654bdc5f411ea545a95b2dfecd74e9

**Comment by LisaAlmarode** [comment]
Things mostly sync but see the screen shot in issue #419...

**Comment by LisaAlmarode** [comment]
It's not entirely clear what the optimal behavior is for corner cases.  Having a second browser of (PB/SUB) open makes test results sticky in some cases but not all.  Should stickiness depend on which browser ran the tests?  Should clicking on a difference class and back clear results in all browsers?  

select the same test class in both SUnit and a project browser/SUnit tab, e.g. TonelWriterForCypressTest. 
Run one test in the Sunit browser.  The PB nicely updates icons.
Click on a different class in the SUnit browser and back to TonelWriterForCypressTest.  The icons in the PB vanish.

However, if you do this vice versa between SUnit and BP, the icons are still visible after reselecting the class and SUnit tab in the PB.  One or another of these isn't correct.

@dalehenrich, how sticky is too sticky?

**Comment by dalehenrich** [comment]
@LisaAlmarode ... I'm not exactly sure what you are asking, but when it comes to stickiness, my inclination is that the test results should show the results of the last test run in the pane itself ...

If I run the tests in an SUB, then I want those results to be sticky until I re-run/rest the tests ... if I run the tests in the PB then I want the same thing to be true ... it's a bonus if the test results (for the same test) are updated in all of the test browsers open on that test, but I wouldn't make that a requirement ... I want the SUB to record and show the results of my last test ... I am smart enough to know when I want to rerun the full test suite versus running and re-running the individual failing tests that I am working on and I'm annoyed when a previously green tests goes to envelope, because I am not smart enough to remember whether or not it was green or red before it turned envelope and I have to rerun the envelop tests because I don't want to lose track of the tests that failed the last time I ran the tests and envelope means I don't know what the status for that test was the last time I ran the tests ...

I've seen in the past behavior where the test result is cleared when I save a test method ... I would rather that the test results were persistent across method changes ... I think I understand the rationale behind changing the status of the test, but for me I want the window to represent the results of the last time I ran the test regardless of the edits I have made ... 

I don't know whether this helps or not --- I realize that the SUB behavior might not be currently implemented to support "what I want" --- but you asked my opinion on stickiness so I'm giving it to you ...

**Comment by LisaAlmarode** [comment]
Closing in favor of #432.  While some stickiness is nice, I feel it's a bit too sticky... but we're confusing Eric so will file a separate bug once we've got everything at the same stickiness level.
