### ISSUE TITLE
Jadite doesn't exit cleanly on OOM

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#414]
If you run out of GemStone memory, you lose your session (reasonably).  
However, Jadeite won't close cleanly.  The login dialog closes, but the console and PB I get the error:

JadeiteProjectsBrowserPresenter does not understand #halt

And I have to use task manager to shut down those two windows.

To try this at home, fill memory using
| temp |
temp := Array new.
1000000000 timesRepeat: [temp add: Object new]

**Comment by dalehenrich** [comment]
What does your gem log look like when **you** run out of memory?

**Comment by LisaAlmarode** [comment]
I'm not reproducing the problem today.  Possibly there was some order in which I closed the windows or something interesting that had gone on previously in the image.  Eric, if the error message isn't suggestive to you, you can close this.

**Comment by regkrock** [comment]
Since I am still on 3.0.50 this may be not relevant but I am getting errors because of mark/sweep issues. Only seeing these the last two or three days.

**Comment by ericwinger** [comment]
@LisaAlmarode  I'm curious if you start seeing the error by doing this - 

- Compile your 'fill memory' code into a method like ``RowanQueryService>>implementorsOf:``
- Then browse implementors. 
- If it fails oddly, send me the ``Jadeite.errors`` file

I speculate that the failure you originally saw was an out of memory within a service call which may not be handling unexpected errors well. We may have to somehow poison the jadeite session object in order to keep Jadeite from trying to do server calls against a dead session which (presumably) is where the failure to exit got in trouble.

**Comment by LisaAlmarode** [comment]
Within a service doesn't create a problem and again cannot reproduce... closing for now.
