### ISSUE TITLE
(3.0.60) autocommit not done after successful doits

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#427]
I know that the autocommit feature was "documented" as a commit being applied after every service request but apparently not every interaction with the server is done through a service request ... at the end of the day I think that all server interactions should have an autocommit applied ... a workspace/doit is an obvious place that I would want an autocommit at e performed since I may be modifying persistent state ...

At this point I am now curious what else is not protected by a commit ... perhaps a little bit more explicit information about which operations are covered by a service request is in order ... otherwise I will be compelled to be manually committing on the off chance that I may lose my work ... 

I'm marking as February just so the issue gets noticed ... I don't personally expect any new work to be performed since I'm not sure whether or not the customer cares about autocommit ...

**Comment by LisaAlmarode** [comment]
GBS's autocommit semantics are that changes to classes and methods are automatically committed, but there's no commit after ad-hoc executions even if they might have the effect of changing persistent data.   I think in Rowan debugger method changes trigger autocommit, unlike GBS, and I think Rowan's behavior is better/more intuitive.

We should to get Martin's input since he was the driver for the GBS feature and may remember the rationale.

From GBS:
"Auto-commit is only available for sessions in automatic transaction mode. In Auto-commit mode, every code change made in the browsers is automatically committed to the repository, which also starts a new transaction. Changes made in inspectors or debuggers do not trigger the commit, although any changes that have been made are included in the next commit.
Auto-commit avoids the risk of losing work, but each method change updates your transactional view of the server. This may result in unexpected changes in a multi-user system in which other users may commit changes to server objects you are using."

**Comment by dalehenrich** [comment]
... I've been used to tODE's autocommit which commits after everything .... and there is never a time when you worry about whether or not you will lose your work ...

Of course this comes up because of the relatively frequent crashes/hangs/OOM events that are frequent enough to be troublesome ... I can't remember the last time I had a tODE crash, but it wouldn't matter much because the only thing you lose is the doit/operation that caused the crash ...

I've only been living with tODE-style autocommit for 5-6 years and I've gotten used to not thinking about having to commit ... I'm sure that if we document the places where folks have to worry about managing their own transactions it will be fine ... and a stable client (when we figure out where these crashes are coming from) means that if we don't have 100% of commits after server interactions, the exposure will be pretty low ...

**Comment by ericwinger** [comment]
Have a fix for this in 3.0.61. I believe it is stable enough for our next release. If not, we can pull it out as it's contained in this commit - https://github.com/GemTalk/Jadeite/commit/01955cdbb37311263cb4d40b2dd5b24f14d6ece4

**Comment by ericwinger** [comment]
I'm unclosing this. Found some problems in my solution.

**Comment by ericwinger** [comment]
Would like to fix this in the next customer release of Jadeite targeted for April. Changing label.

**Comment by ericwinger** [comment]
Fixed in 3.0.67 https://github.com/GemTalk/Jadeite/commit/7186aeed1653a645aa2fae7de5285236dd2d51de
