### ISSUE TITLE
I'm not on branch "HEAD", really

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#431]
I have to go to the command line to get the right Rowan to go with my Jadeite, since I can't checkout a tag from Jadeite.

When I do this, my browser tells me I'm on the branch HEAD.  I'm detached head, and this may mean I'm not really on a branch at all, but I'm pretty sure I don't want to see HEAD right there. In fact what I'm NOT on, as far as I understand , is HEAD.  

benton:/benton1/users/gsadmin/GS643215/myrowan/Rowan> git status
HEAD detached at Oscar-3.0.60

![image](https://user-images.githubusercontent.com/13142166/52254090-7c8da400-28c0-11e9-9fa0-e1ad6b77052b.png)

**Comment by ericwinger** [comment]
This comes straight from Rowan. ``(RwProject newNamed: name) currentBranchName``

I'll reassign to @LisaAlmarode  and @dalehenrich  for discussion on what the right answer is.

**Comment by dalehenrich** [comment]
This is related to issue #311. 
With git here is what happens when you checkout a tag ... 
```
rogue:Rowan>git checkout v1.2.5
Note: checking out 'v1.2.5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at d7b97e1... Merge pull request #426 from GemTalk/candidateV1.2
```
And `HEAD` is what is returned by `git rev-parse --abbrev-ref HEAD` the command to extract just the branch name in Rowan:
```
rogue:Rowan>git rev-parse --abbrev-ref HEAD
HEAD
```
... and here is the result of `git status`
```
rogue:Rowan>git status
HEAD detached at v1.2.5
nothing to commit, working directory clean
```
I think that the status message has a little more useful information and the use of `git rev-parse --abbrev-ref HEAD` is an attempt to extract just the branch ... and I guess git considers `HEAD` to be enough of an answer:)

We have lots of options for fiddling with this, but I think that at the end of the day, we need to decide how far we will go in trying to provide the level of git functionality that is available from the command line ... 

In tODE I have a minimal level of support for the basic common operations, but there are times when I turn to the command line to do any of the more complicated operations ... This also gets complicated by the fact that there are multiple workflows that are supported from the command line and each workflow would need it's own --- different development groups follow different workflows ... 

From watching the progress of Iceberg (Pharo's GUI for working with git), I don't think they've quite got everything worked out and they've been at it for 3 years ... 

Ultimately we need to do more to support git and it really is something that we're not just going to solve in a week or two:)

**Comment by LisaAlmarode** [comment]
All I ask is if Jadite can't give me useful information, at least pretend to care and give me a more soothing message, not something obviously blatantly incorrect... as long as I'm required to go to the command line and checkout a tag, it's a situation that we need to be prepared to deal with...

What's wrong with the entire line:
   "HEAD detached at Oscar-3.0.60"
that contains what I really need to know.

Alternately, if Jadeite gets the urge to print the actual word "HEAD" it could instead display some other hardcoded error response... e.g. "<detached head>" or <no branch info> or whatever.

**Comment by ericwinger** [comment]
@LisaAlmarode  The entire line is not available from the command. From a detached state, Rowan gives me back: 
```
(RwProject newNamed: 'Rowan') currentBranchName 'HEAD'
```
I would need different support from Rowan to give the entire line.

**Comment by dalehenrich** [comment]
>What's wrong with the entire line:
"HEAD detached at Oscar-3.0.60"
that contains what I really need to know.

Nothing but I will have to see if I can find another git command to extract the information that you want ... also do you really want to have this addressed before Thursday? I wasn't planning on touching Rowan, but if it is needed, I will do it ...

**Comment by dalehenrich** [comment]
@LisaAlmarode, as I splash about with git commands here are two different options I've come across:
```
rogue:Rowan>git rev-parse HEAD
d7b97e1c1266d876b53b46a954eadc6d61cf0027
rogue:Rowan>git rev-parse --short HEAD
d7b97e1
```
In both cases you are getting a SHA ... which is better than HEAD ... but I haven't determined whether these two variants will evergive you the name of the branch you are on ... in git, `HEAD` is the "name" of the detached branch ... so I'm still  splashing around as I try to avoid getting into the business of parsing `git status` output:)

**Comment by dalehenrich** [comment]
Looks like the winner is: `git branch | sed -n '/\* /s///p'` (from an answer in https://stackoverflow.com/questions/6245570/how-to-get-the-current-branch-name-in-git .. not the top answer:) ...
for tag:
```
rogue:Rowan>git branch | sed -n '/\* /s///p'
(HEAD detached at v1.2.5)
```
for branch:
```rogue:_home>git name-rev --name-only HEAD
master
```
for arbitrary sha:
```
rogue:Rowan>git branch | sed -n '/\* /s///p'
(HEAD detached at d6348f0)
```
for Jadeite:
![image](https://user-images.githubusercontent.com/623951/52298566-12184a80-2938-11e9-885c-384b1c983131.png)

@LisaAlmarode If this looks good, I'll check it in ...

**Comment by LisaAlmarode** [comment]
That looks fine...  I'll be very happy with the tag, but the sha really would be enough, since I can match that to the release. I'm actually not fussy, I just didn't like the plain "HEAD".

**Comment by dalehenrich** [comment]
[fixed in this commit](https://github.com/GemTalk/Rowan/commit/d798d926b52b685c1140957eeb47ccbd1400f144)
