### ISSUE TITLE
(3.0.62) error message from previous compile error hangs around after error fixed

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#440]
Marking for Feb release, since it should be looked at and decision made whether it belongs in Feb or not.
![image](https://user-images.githubusercontent.com/623951/52679467-07d2ef00-2eea-11e9-97dc-5ee439f4b615.png)

**Comment by ericwinger** [comment]
@LisaAlmarode  I'm not seeing compile errors hang around in my limited testing. Can you reproduce?

**Comment by LisaAlmarode** [comment]
This can be reproduced in 3.0.74 in a multi-tab environment.
- Have different methods in two tabs in the PB
- edit one to generate a compile error.
- switch to the other tab.  Continue seeing status bar.

Autocommit was on for this case but it doesn't matter.

![image](https://user-images.githubusercontent.com/13142166/62101004-b4125300-b248-11e9-8bc1-2c3b25da95ea.png)

**Comment by ericwinger** [comment]
The status bar and auto commit tabs were in the scope of the browser, not the presenter (tab). Moved both to the presenter so that each tab has it's own unique status bar now. Might want to take an extra look to make sure that the auto commit button wasn't perturbed in the process as that had to get moved to the presenter as well.
