### ISSUE TITLE
(3.0.62) suspicious code in RowanClassService>>hierarchyClassServiceFor:

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#441]
I got an error in project browser while running a test and here's the snapshot of the debugger:
![image](https://user-images.githubusercontent.com/623951/52680194-7618b100-2eec-11e9-94ce-0fdc623545d3.png)
You can see that the `className` argument is a symbol, but the comparison `className = 'Object'` will never return true ... because the className is a Symbol ... don't know if there are other tests that are sensitive ..

At this point it is possible that the class structure is actually messed up ... I was trying to look at the class structure when I hit this bug ...

Putting in Feb label, because I think this is a quick one to fix ...

**Comment by dalehenrich** [comment]
In case it _is_ relevant, I've included another debugger that came up when I tried to use the dictionary browser to debug my situaion ... again it is possible that I've messed up the hierarchy and am just trying to figure out what my class structure looks like ... Here's the screen shot:
![image](https://user-images.githubusercontent.com/623951/52680566-b75d9080-2eed-11e9-9060-7b382c0a81fd.png)

**Comment by dalehenrich** [comment]
I did mess up the class structure ... so the errors may not be relevant, but the symbol/string comparison is the target of this bug report

**Comment by ericwinger** [comment]
Need to take a look and categorize as either immediate or defer until April.

**Comment by ericwinger** [comment]
Fixed in 3.0.63. https://github.com/GemTalk/Jadeite/commit/6f8e7e15b72ca16014b96b7f0776014c1c57fbc4 Also took a pass and made sure that ``RowanClassService >> name`` & ``RowanMethodService >> className`` were always strings. Didn't take out the call to ``asString`` in the method referenced by this issue due to the proximity of release and the chance that there are still symbolic class names out there.
