### ISSUE TITLE
Sunit tab fail to enable/disable right side icons related to selection (3.0.73)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#494]
Say you are on the SUnit tab in the PB, with say RowanSample1Test being the class you have selected.

There are 5 icons in the sidebar; two apply to all 5 tests, three are just for selected test/s.

With the fix for #179, the little guy is enabled on first entry which is nice, and reset is fine.

The three middle selected-test icons are all a bit wonky:

With nothing selected:
  run triangle is disabled (good)
  run and measure time clockface is enabled (wrongly but benignly ) and will report a time of 0
  debug-it window with sunit is enabled (wrongly) and does nothing (which is bad; it might mislead you into thinking all tests were run without error).

With one or more tests selected:
   run triangle is still disabled (bad - this icon never seems to be on)
   The other buttons behave correctly.

**Comment by ericwinger** [comment]
I believe that the enablement of the three menu options and tool bar buttons are better now. Each should disable & enable based on selection. 

A note about run selected (triangle) ... We're overloading the accelerator key Ctrl-Shift-S when the SUnit tab is shown. If different methods are selected in the method list pane and the sunit tab, we try to run what is presumably most intuitive based on the user's cursor position and other factors. 

Yet, there might be some non-obvious behavior. For example, if no method is selected in the sunit tab but a method is selected in the method list pane, Ctrl-Shift-S will run the selected test in the method list pane. Another example, If different methods are selected in both, Ctrl-Shift-S will run the selection in the pane where the cursor is. 

In order to have the convenience of the accelerator key, some ambiguity is necessary in this case. Hope that is acceptable.
