### ISSUE TITLE
minor error dialogs (3.0.73)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#495]
Minor error dialogs sprinkled about.

- [x] In PB, on the sunit tab, if you attempt to maximize the method pane (no reason to do this, other than not knowing that the white box with the green top would do), you get an error dialog with "JadeiteSUnitInClassPresenter does not understand #maximizeCode".

- [x] A nice chance to try out the Logger Browser.  When I turn on logging and open the logger browser, I could only see a little bit of the string.  I double clicked on the entry in the logger browser, and get a dialog with: "Array does not understand #inspect. "   The logger browser is a bit dull, in fact.

I also was attempting to close a project tab (before I found the wee x way off the the far right), and managed to get a error dialog "ListView does not understand #clearSelection".  But I can't reproduce this now.

**Comment by ericwinger** [comment]
I fixed the first bullet item but the second (inspect in logger browser) presents some challenges. The browser tries to open a dolphin inspector, not a jadeite inspector. Because runtime Jadeite is currently stripped of all its client inspectors, there is no inspector available to open. I've disabled this feature in the runtime as the intent is for a developer with a dolphin development environment to analyze the log. 

I'm open to ideas on how to make logging more useful.
