### ISSUE TITLE
Class rename also updates method sends (3.0.76)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#513]
If you have a method send within a method that is the same as the class name, the method name gets updated.

The class is named ``RenameTest``.
instance methods:
```
RenameTest
^self class
test
^self RenameTest
```

When I renamed ``RenameTest`` to ``NewName``,
the ``RenameTest`` method was unchanged.
the test method was updated:
```test
^self NewName
```
which will fail since there's no method ``NewName``.
It would be more serious if it was likely that this occurred under normal conditions - I just stuck a 'self' in front of the class name so I would be able to test the rename.

This is a good time to also request that I not be informed if no methods were updated.  That extra dialog I don't need.

**Comment by ericwinger** [comment]
Note - updated issue report for easier to read formatting

**Comment by ericwinger** [comment]
Removed the dialog in 3.0.77 but the primary complaint is a Rowan issue as the recompiled method behavior is handled there. Closing. 

@LisaAlmarode - Can you create a Rowan issue for the primary complaint?

**Comment by LisaAlmarode** [comment]
I'm afraid we can't just close issues that show up in Oscar if we are waiting on a fix in Rowan.  They are still bugs.

**Comment by LisaAlmarode** [comment]
Opened rowan bug for Eric:
https://github.com/GemTalk/Rowan/issues/509

**Comment by dalehenrich** [comment]
I refer you [this comment](https://github.com/GemTalk/Rowan/issues/509#issuecomment-534724450) ... the mistaken edit is occurring [right here](https://github.com/GemTalk/Rowan/blob/candidateV1.2/rowan/src/Rowan-Services-Core/RowanClassService.class.st#L815-L818) in RowanClassService code.

**Comment by ericwinger** [comment]
@dalehenrich is correct. Services is making the changes to methods and is responsible for updating renamed classes in method source properly. (Oversight / Faulty memory on my part) 

I believe a fix is to look for references to the old class rather than the old class name in  ``RowanClassService>>renameClass:To:`` using ``ClassOrganizer>>referencesToObject:``. That will eliminate the immediate problem. 

However, ``referencesToObject:`` does not return the source offset of the referenced class. If I had the offset, I could surgically replace class names in method sources and eliminate the substring search & replace referenced [in this comment](https://github.com/GemTalk/Rowan/issues/509#issuecomment-534724450).  @dalehenrich Do you know if there is a method that will return references to a class with the reference's source offset? I couldn't find one in ``ClassOrganizer``

If there isn't a way to find the references to the class object with source offsets, maybe we can just live with a substring search / replace. After all, we do display the changed methods so the user can review and fix any mistakes. 

Thoughts @LisaAlmarode?

**Comment by dalehenrich** [comment]
> @dalehenrich Do you know if there is a method that will return references to a class with the reference's source offset? I couldn't find one in ClassOrganizer

@ericwinger I don't know of anyplace other than `ClassOrganizer` for doing references ... in the past I have written custom methods for tODE, but I don't think I've done anything quite like what you are looking for ... should be possible to write something that does that though

**Comment by ericwinger** [comment]
I've improved the reference search to only search for references to the class, not the class name. https://github.com/GemTalk/Rowan/commit/b2074883f06323c3a6cf38524ec1bd5a5be4bdf6

@LisaAlmarode  Dale's suggestion to write up an object reference search with offsets is a good one. However, after reviewing the ``GsNMethod`` code, I think that's a bit outside the scope of our November release. If I'm correct, can you remove the ``November 19`` label?

**Comment by LisaAlmarode** [comment]
The basic issue is fixed, so I am fine to remove the November 19 label.

I'm not entirely sure I follow the details of the discussion. Are there some behaviors that are incorrect, or do you want to improve the underlying code?

(Boy, do I dislike autocomplete!  It slowed things down like crazy (perhaps since I'm remote), and I accidentally entered wrong code.  I suggest the default be off).

**Comment by LisaAlmarode** [comment]
As of v3.2.12, my method doesn't get renamed; this issue is fixed. 

Opened issue #974 for the converse, methods on that class that refer to that class fail to recompile, which I think is the point of the later discussion under this issue.
