### ISSUE TITLE
CTL-SHIFT-t and CTL-SHIFT-f shortcuts for ifTrue: and ifFalse:

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#523]
Customer request ... not  a problem if out of scope for November release

**Comment by ericwinger** [comment]
@dalehenrich do you think that the customer would accept a different ``Ctrl-Shift-`` key? Currently, ``Ctrl-Shift-F`` (& ``Ctrl-F``) are taken for class find (& method find).

Also note, I'll need to make these menu options as well because accelerator keys in Dolphin's ScintillaView class are frustratingly limited.

**Comment by dalehenrich** [comment]
I would say that you can define whatever short cut keys make sense in the Dolhin environment

**Comment by ericwinger** [comment]
Ctrl-Shift-D ``ifFalse:[]`` and Ctrl-Shift-F ``ifTrue:[]`` were added in 3.0.78.

**Comment by LisaAlmarode** [comment]
I think if we use control-shift-F  that really should be ifFalse, and control-shift D could be the other one (D is for derecha). The current choices are anti-mnemonic...

**Comment by ericwinger** [comment]
Oh, sorry.  Ctrl-Shift-T is for ``ifTrue:[]``.  Ctrl-Shift-F is for class find, so shifting over one key to Ctrl-Shift-D, while anti-mnemonic, is easy for typing. Maybe we should say that it's "typonic"?
