### ISSUE TITLE
(3.0.77) format shortcut doesn't work in debugger text pane ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#536]
I didn't check whether or not the format menu item is present ... if it isn't, it should be and the shortcut should work

**Comment by ericwinger** [comment]
Found and fixed that before issue was reported. Available in 3.0.78.

**Comment by LisaAlmarode** [comment]
The usual reformat source shortcut is control-shift-O.  

In 3.0.78, In the debugger, the reformat menu item works, but claims to use control-R as the shortcut.  In fact, either control-R nor control-shift-O perform a reformat (they put little red DC2s or SIs in the source pane)

I think the debugger also creates sticky reformatting (reformat, click off, don't save, return to method later).

**Comment by ericwinger** [comment]
> In 3.0.78, In the debugger, the reformat menu item works, but claims to use control-R as the shortcut. 

@LisaAlmarode I'm a bit confused. Here is what I see in 3.0.78. 

![image](https://user-images.githubusercontent.com/36212516/66520802-b55cc900-ea9e-11e9-9417-9a891029d1fd.png)

**Comment by LisaAlmarode** [comment]
![image](https://user-images.githubusercontent.com/13142166/66534594-8d378f00-eacb-11e9-9c38-3703d208ac2d.png)

**Comment by ericwinger** [comment]
Oh wait, ``Reformat Source Ctrl+Shft+O`` was fixed in the debugger to work in 3.0.78 but the shortcut was fixed in 3.0.79. 

I'll close for review when 3.0.79 is release.

**Comment by ericwinger** [comment]
Also see #542

**Comment by LisaAlmarode** [comment]
Working in 3.0.79, but there's still a stickiness issue, which is described under issue #550.

**Comment by LisaAlmarode** [comment]
While reformat works fine, there's still a stickiness problem.  This is only in the debugger; the PB working very nicely (issue #550), so reopening this to handle the specific issue with stickiness in the debugger.

In v3.0.81, if you are in the debugger and reformat, and click on another method it asks you if you want to stay on the changed method; if you say no, and then later click back to the original, you'll see the supposedly-discarded reformatted text. 

It also preserves text code changes to the method, so the method source may be wrong, not just differently formatted.  text changes are only preserved if you've done the reformat.

I'm taking off the november since this is a bug, but not terribly serious

**Comment by LisaAlmarode** [comment]
Closing this, the leftover bit is filed as issue #610.
