### ISSUE TITLE
(3.0.77) refresh menu item would be useful in breakpoint browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#544]
I just got done disabling 3 or 4 breakpoints in the breakpoint browser, but without a refresh, I couldn't easily tell whether or not I had disabled all of the breakpoints I wanted to, so I had to close and reopen the breakpoint browser to see which ones were left ... it might make sense to automatically remove a method from the list that has had it's last breakpoint removed ... I think arguments can be made on both sides ...

**Comment by LisaAlmarode** [comment]
This is not just an enhancement. Having to open a new browser in order to see methods that have had breakpoints added is a clumpsy workaround.

Jadeite's theme is that things automatically update, so probably newly breakpointed methods should automatically be added. as well as removing methods with the last breakpoint removed. But an update would be enough if this is too much to paste onto a method list browser.

... without being able to update, you can use the remove all breakpoints menu item... and remove breakpoints that are not even visible.

**Comment by dalehenrich** [comment]
There **are** enabled and disable breakpoints and being able to browse `disabled` breakpoints would be useful ... a enabled/disabled/all filter on an automatically updating breakpoint browser would meet my use cases ...

**Comment by LisaAlmarode** [comment]
I'm not aware of how to enable or disable individual breakpoints, it's just a system-wide setting... am I missing something?  You can remove them, but then they are removed and can't be browsed.  

The system wide disable breakpoints setting does seem to apply to only preexisting breakpoints; if breakpoints are disabled and you create a breakpoint, the new one not disabled.  And the disabled breakpoint is not highlighted in browsers.

**Comment by dalehenrich** [comment]
@ericwinger and I talked about the need for a more detailed breakpoint browser and that's what I'm referring to ...again this is a future direction not an immediate requirement and whatever we do for Nov (if anything) won't be a final solution

**Comment by dalehenrich** [comment]
see #545 for the report that kicked off the discussoin ...

**Comment by ericwinger** [comment]
The new breakpoint browser should handle breakpoints automatically. Plus, it has a refresh button just in case. Fixed in 3.1.0.
