### ISSUE TITLE
Project Pane in Project Browser has lost multi-select (3.0.78)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#559]
Used to be (and in UG) that you could select multiple projects in the project pane of the project browser. Now, I can't select more than one.  

Multiple select of projects is working in the console.

**Comment by ericwinger** [comment]
That's correct. When I added the (NONE) project, it became obvious that a multi select was not going to work because of the weird nature of (NONE). Without going into a long discussion, managing multiple selections was going to be very difficult and probably not ever going to be right. Making it single selection was much cleaner. ... The project list is still multi-select for operations for multi-project operations.
