### ISSUE TITLE
Undo/Redo in method list browser (3.0.81)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#583]
When you first arrive at a method in the Project Browser, redo/undo/save are disabled.  
When you first arrive at a method in the Method List Browser, redo/undo/save are enabled.  

This is not correct: enablement should be the same.

(also note: in the Project Browser, delete is enabled, which deletes under whereever the cursor is when you bring up the popup).  
Also, I see there's no edit menu on the Method List browser).

----
The undo-redo with reformat allows a sequence to get you into a harmless but inconsistent state.

- in method list browser, reformat the method. 
-click undo
-click redo
The method is now in the formatted state, but with a yellow background... if you click away and back it does not ask if you want to save changes.

**Comment by ericwinger** [comment]
Enablements are all fixed in 3.1.0 pre-release2. 
Undo/redo sequence was fixed in a prior checkin. 
There is an `Edit` menu on the method list browser, but it's not consistent with the source pane pop-up menu. If we want these to match like the projects browser, please open a separate bug with guidance on how to distribute the existing `Edit` menu items.

**Comment by LisaAlmarode** [comment]
Nits on the delete menu item filed, also filed issue #772 on the edit menu.  I have other follow-on nits.  Like hydra, one issue closed but seven issues grow back...
