### ISSUE TITLE
Would like changed method indicator on tab

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#584]
If multiple tabs are open in a project browser, finding the tab with your changed method is overly cumbersome. Adding a `*` or making the tab red to show changes are unsaved would be helpful. It also might be valuable to add a change indicator on the `Method Source` tab itself.

**Comment by ericwinger** [comment]
Added a changed indicator in the system tab if the method has unsaved changes. Also added a `Revert` method menu option to undo changes without having to change methods.  `Revert` will ask for confirmation before reverting. 

![image](https://user-images.githubusercontent.com/36212516/76884043-4e57f300-683a-11ea-95c6-b98e8dc03c5c.png)

**Comment by LisaAlmarode** [comment]
I like the stars and the revert. feature.  

 - [x] After you save the method change... the star doesn't go away.  Not until you select a different method.

 - [x] the revert menu option is present on workspace menus, and enabled if you make edits.  But instead of reverting to saved version, it reverts all the way to an empty workspace. 

 - [x] the revert menu option is present in the breakpoint browser text pane, and enabled if you make edits.  It results in an MNU.

**Comment by ericwinger** [comment]
Fixed in 3.1.0pre-release4
