### ISSUE TITLE
PB Method drop-down menu intermittently loses "Go to defining package" (3.0.82)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#599]
The Project Browser popup and drop-down Method menus normally include an item "Go to defining package <packagename>", which is disabled if no method is selected, etc.

However, if you set focus into the method text, this goes missing from the drop-down method menu, which now oddly ends in a line.  This is still there on the pop-up menu.

You can select different methods, and the menu item is still missing.  However, selecting a different class does a reset and makes the menu item visible again.

![image](https://user-images.githubusercontent.com/13142166/67519959-c7bd3200-f65c-11e9-963a-c2734287b5b8.png)

**Comment by ericwinger** [comment]
Old code was arbitrarily removing menu items beyond an expected size. See `methodMenu:` implementors. 

Once that bad code was removed, problem was fixed. However, that introduced a side effect such that method source menu items - break, browse implementors/senders - wouldn't remove themselves properly. Now we add/remove those latter three menu items in the same method that adds them which is safer.  See `RowanMethodService>>appendToSourceMenu:presenter:`

Fixed in 3.0.92pre-release2
