### ISSUE TITLE
Double click no longer expands hierarchy view

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#641]
Customer reports undesirable change in double click action on hierarchy view from 3.0.65 to 3.0.87. Double click no longer expands the entire list of subclasses. 

> Double clicking on the superclass (DBO_BOTTest) and then expanding the tree node showed all subclasses in the previous release.
> Now it only shows the one subclass which was already visible.

![image](https://user-images.githubusercontent.com/36212516/69260692-218a1c80-0b75-11ea-8777-6cf713c314b4.png)

Or try with TestAsserter.
![image](https://user-images.githubusercontent.com/36212516/69260739-3797dd00-0b75-11ea-9abc-6a940eb6dc48.png)
![image](https://user-images.githubusercontent.com/36212516/69260760-3ebeeb00-0b75-11ea-95f7-ad25934208e3.png)

**Comment by ericwinger** [comment]
Should be fixed in 3.0.89. Does a full expansion and has a menu option as well.

**Comment by LisaAlmarode** [comment]
Compared the behavior in 3.0.65 and 3.0.89-1.  Very happy to see that not only is the behavior fixed from 3.0.87-era, the full expansion now doesn't have stealth siblings - expansion shows the full set of classes, which fixes the unfixed complaint I had in the otherwise closed issue #156.  Not sure if there's a downside... doesn't seem slower than 65 to me.

@dalehenrich should review issue #561, since I suspect that is fixed by this too.

If I select Object and select the expand hierarchy, it runs out of memory and kills the session (with 1.1GB toc).  Probably should have some kind of handler.

**Comment by dalehenrich** [comment]
@LisaAlmarode I have updated to 3.9.89-1 **because** there is support for full hierarchy viewing ... it never occurred to me to double click on a class to get full hierarchy ... but now there is a menu item ...

**Comment by LisaAlmarode** [comment]
I find it difficult to characterize the behavior in 3.0.65 (that is, there appears to be no logical construct that can be fitted over it); the changes in earlier 3.0.8x make things worse.  I'm not going to say the current behavior is optimal; but I think it might be a reasonable compromise.  I've filed separate issue #645 on the absence of perfection.

in 3.0.89 release, I can select Object and expand and it takes a while but does complete.
