### ISSUE TITLE
(3.0.89) Cannot use breakpoints or self halt when using debug icon in SUnit browser 

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#656]
I'm trying to simulate the feature requested in #655, but using halt or breakpoint ends up with an `infinite` stack of ddebuggers:
![image](https://user-images.githubusercontent.com/623951/70190997-4e2d5080-16ac-11ea-8eb7-6a3718c68d4e.png)
I would like to deal with each debugger at a time ... in tODE, I call the feature something like `debug first`and the first debugger is brought up and the SUnit process is blocked until the debugger is closed or proceeded ...

**Note** that none of the debuggers are usable after closing the `out of stack` notification, as they remain blank...

**Comment by ericwinger** [comment]
I believe the fix for #748 should handle the case where Jadeite gets in trouble when it encounters a breakpoint while building a debugger. This will be available in 3.1.0. 

In my limited testing, I was able to debug, fix, and continue two broken tests using the `debug` button in the SUnit tab and SUnit browser. 

@dalehenrich There are many places where setting a breakpoint in the current Jadeite release `3.0.93` can cause the debugger to get in trouble.  If I know more about where you set the breakpoints for this case, it will give me more confidence that I have the problem fixed. 

Can you or @LisaAlmarode setup a reproduction case?  Perhaps using one of the Rowan services tests?

**Comment by LisaAlmarode** [comment]
I wasn't able to produce a problem while putting breaks in display methods; I get some unattractive dialogs, but nothing entirely broke. Given the bug is well over two years old and probably on 3.5, and there are so many changes in breakpoint/debugger support in 3.7...  closing: @Dale can reopen if he's seen this (and not reported separately) in 3.7/Rowan 3.
