### ISSUE TITLE
Would like hot keys in debugger

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#664]
Kind of like navigating vim, it would be nice to have Ctrl- characters to step, step into, step through, step over, step out, and resume. Keeping them together on the keyboard would be helpful. Like J,K,L,, etc.

**Comment by ericwinger** [comment]
Fixed in 3.1.0. Used Ctrl-F10, F11 and friends for debugger navigation.

**Comment by LisaAlmarode** [comment]
-- if you select multiple projects in the console, the checkout git branch is disabled, but the checkout git tag is enabled.  The checkout git tag gives an error, so that menu item should be disabled too.

-- if you checkout git tag on one of the Rowan projects, like STON, then it really checks out tag on all **but you can't tell**... you have to explicitly refresh.  I think after a git checkout operation, it would be worth the extra time required to automatically do a refresh. 

-- this is just my not really understanding tags v. branches.  When I have checked out a tag, am I still in some sense on a branch?  I see my "branch" as "HEAD detached at <tag>", with no mention of "oscar" anywhere.  When I went to the checkout branch menu I felt a moment of unease since while I thought I was on oscar and in theory might be able to use the latest on that branch... I didn't see anyway to check that was in fact the branch I was generally following.

**Comment by LisaAlmarode** [comment]
Reopened by mistake.

The key shortcuts are on the menu and appear to work but - I usually don't remember or use keyboard shortcuts, and these are much more baffling and non-intuitive than the others, so checking all the details will have to set with someone who would find these useable.
