### ISSUE TITLE
(3.0.91) Would like debugger to remember it's last location after resume

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#665]
@dalehenrich noticed that if he is debugging and repeatedly opening debuggers, when he moves the debugger window, it is annoying if the next debugger opened jumps back after resume. 

I'm not sure how dolphin decides to position windows but using a "last position" methodology might work. 

If #664 is implemented, that could also help.

**Comment by ericwinger** [comment]
Debugger now retains it's last position for the life time of the executable. In 3.0.92pre-release2.

**Comment by LisaAlmarode** [comment]
Testing in 3.0.92-2, I thought this wasn't working... but turns out it requires that the debugger exit naturally.  If you close the debugger window using the (Windows) little x icon on the upper right (or the Windows drop-down in the upper left sparkle), the position is not remembered.  

However, if you run to completion, the location is remembered.

Reopening this since it does appear to be not entirely fixed, but if remember-on-close is something that can't be handled in dolphin, it's not a big deal for me.

**Comment by ericwinger** [comment]
This seems to be working for me now. Capturing the last position a little earlier in 3.0.92.

**Comment by LisaAlmarode** [comment]
Remember on various kinds of close is reliable now.
