### ISSUE TITLE
Copy stack from walkback notification; get <stringclass> DNU #as<OtherStringClass> (3.0.94-4)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#718]
Similar to the side issue mentioned in issue #713, but specific classes are different.

In this release, it's String does not understand #asUTF8String

![image](https://user-images.githubusercontent.com/13142166/74365485-1107cd80-4d83-11ea-8aea-049faa045f1c.png)

Happens reliably anytime I want to copy a stack.

**Comment by ericwinger** [comment]
This appears to be odd stripping behavior. `String>asUTF8String` is implemented and sent in the development image but appears to be stripped out of the runtime.  The image stripping log shows the method is sent and does not log that it was stripped.

The best I can figure out is that a message is sent in `asUTF8String` which sends another message to a third method which has a message send to an unimplemented message. Since these 3 messages are only sent in this code path perhaps all three methods were stripped out. 

It's probably not a good idea to send the `asUTF8String` anyway. It's from a contributed package and `asString`  is in the base and perfectly fine to use. 

Send `asString` instead.
