### ISSUE TITLE
Add 3.6.0 client libs to Jadeite

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#728]
Not sure if there are any gci changes.

**Comment by dalehenrich** [comment]
FWIW, I **did** get an error when I tried to replace the 3.5.0 gci libraries in the bin directory with a set of 3.6.0 gci libraries:
![image](https://user-images.githubusercontent.com/623951/75117137-afb5e900-5623-11ea-9cf5-c747897035fe.png)

![image](https://user-images.githubusercontent.com/623951/75117183-1c30e800-5624-11ea-9360-3c7a8cd56cc8.png)

**Comment by dalehenrich** [comment]
... I had actually made a mistake in copying the dlls over - I renamed `libssl-3.6.0-32.dll` file, when the only file that needed to be renamed is `libgcirps-3.6.0-32.dll` ... when I corrected that mistake and added another dll, I was able to login cleanly:

![image](https://user-images.githubusercontent.com/623951/75117476-8a76aa00-5626-11ea-9110-1ec68fe7de8e.png)

So it seems that you shouldn't need to do anything but add the drop down ...

@alexkogan  ... the same trick should work for you , until we get 3.0.93 ...

**Comment by LisaAlmarode** [comment]
How ever are we going to track what 3.6.0 libraries are in the jadeite distribution over time?  Any bugs found in this config, which are probably found with the lastest server builds, will need to be reproduced with the latest shared libraries.  @ericwinger, you'll need to update the 3.6.0 libraries for each version, and be sure to put the 3.6.0 build number in the comments.

**Comment by dalehenrich** [comment]
@LisaAlmarode, @ericwinger, and @alexkogan ... Until Oscar 4.0 is ready, the four of us are the only folks likely to be using Jadeite --- right now I won't consider encouraging anyone else to use Jadeite/Rowan until we have Oscar 4.0 and Rowan 2.0 in the bag .. we are adding 3.6.0, because @alexkogan is interested in using Jadeite for Ernie and indexing code development and even though we only spent a few days last week working on packaging Ernie, I've learned a few important lessons about Rowan ... 

With that said, I don't think it is worth @ericwinger's time to try to keep up with every new server build, especially given the fact that only @alexkogan and myself will be users...

In the longer term I would imagine that we would be building a new Jadeite along with every new server build and we'd have the Jadeite tests (as well as Rowan tests) integrated into the QA process ... 

Right now, @alexkogan and I could get by using my technique to fake out a 3.5.0 gci, but since 3.0.93 has not quite made it out of pre-release, I asked @ericwinger to add the 3.6.0 drop down ...

**Comment by ericwinger** [comment]
I added the 3.6.0 libraries and could login. I named it `64-bit 3.6.0 unreleased` as a reminder to update it once the server product is released. Also marked this as `P1 critical` as another reminder. Adding to `Oscardale` & `Jadeite 7.1.9 port` projects  for yet another reminder.

**Comment by LisaAlmarode** [comment]
I'm okay with including this as a placeholder, with the unreleased label and the specific build undefined; with Eric not expected to keep this updated on any particular schedule. If there is bad behavior the user should copy in the 3.6 library that matches their server. 

I don't have a rowanized 3.6 and I got a gci login error when trying to login with the 3.6 unreleased to my regular 3.6 stone. So I'm marking this closed since the libraries are present, but I cannot assert that they are working.
