### ISSUE TITLE
Changes Browser confusing handling of newlines in method text (3.1.pr3)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#764]
To look at the changes, I added some newlines to a method.  

- [ ] The results show the "on disk" with the newlines, which I know is wrong and caused me to disbelieve the Changes Browser.

It's useful to not report "changes" that are just white space, but white space does need some respect.  Claiming that's what's on disk  is removing credibility.

![image](https://user-images.githubusercontent.com/13142166/78703447-04a17c00-78bf-11ea-8111-b531bdd5b273.png)

- [x] The changes finder has a menu option "include methods with identical source",  This doesn't make a difference in showing the above method.

Methods that have exactly identical source (modify and change back to the orginal) don't show up either. 

I'm not sure what cases this menu item makes a difference

**Comment by ericwinger** [comment]
> The results show the "on disk" with the newlines, which I know is wrong and caused me to disbelieve the Changes Browser.

I inherited a substandard change browser that was substandard but it's what we've got at the moment. However, understanding it's "philosophy" might help. The philosophy of the changes browser (if it ever had any thought put into it) was to ignore blank lines as much as possible in order to let the user compare code differences more easily by putting them side-by-side. 

In the picture below, I've made similar changes to yours but added a couple lines to show what it's doing. Notice that the two identical lines of code are side-by-side with the differences in code highlighted in yellow. This issue's example has nothing to highlight since it can only highlight code currently. 

It might be possible to have the changes browser do a straight text-text comparison, rather than code-code. That might get you what you want but I think it will be less useful to the developer. So I'm inclined to leave this request alone for now. 

We've got an enhancement issue https://github.com/GemTalk/Jadeite/issues/123 to rewrite the changes browser based on modifications instead of monticello patches. Perhaps we can address this problem then? If so, let's put this in the `Future Work` project and perhaps we can open a new issue tied to the rewrite? 

![image](https://user-images.githubusercontent.com/36212516/78838842-e5344d00-79ab-11ea-853f-3006cea30727.png)


Regarding part 2: 

> The changes finder has a menu option "include methods with identical source", This doesn't make a difference in showing the above method.

This was text based and not very useful - all it did was trim blanks. Now, it does a parse tree comparison. If methods are functionally equivalent, no matter the formatting, it will appear / disappear based on the `include methods with identical source` indicator. Fixed part 2 in 3.1.0pre-release4.

**Comment by LisaAlmarode** [comment]
Perhaps we can add a paran modifier after the "Disk" to indicate that this isn't simply "Disk" but say, persistent or cached or per repository or something.  It''s the declaration of "Disk" that I took literally, as one does! and is completely wrong... it made me think I'd accidentally saved to disk...

**Comment by LisaAlmarode** [comment]
Eric, could you make the small label change?  I hate to file a separate bug but that misled me.

**Comment by ericwinger** [comment]
I'd prefer not to choose the name. Could you suggest a complete title and I'll change it?

**Comment by LisaAlmarode** [comment]
How about "Disk Equivalent".  It's not clear, but unclear is better than clear-but-incorrect.

**Comment by ericwinger** [comment]
Fixed in 3.1.0 pre-release5
