### ISSUE TITLE
Debugger Browse Selected Method error on lower methods in stack (3.1pr3)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#765]
Just testing around, as I do, and tried the Browse Selected Method on a method way down in the stack, RowanAnsweringService >> exec:context:inWindow:. This was not friendly.

Note that I'm running as DataCurator.  

![image](https://user-images.githubusercontent.com/13142166/78708310-c5772900-78c6-11ea-83ba-e4060582f1df.png)

**Comment by LisaAlmarode** [comment]
Actually this might be part of a more general problem - I'm seeing the same error when I try to browse methods from the SUnit browser, possibly inheritance issues there.

**Comment by ericwinger** [comment]
Browsing class-side methods was broken. Presumable that's a class-side method in the stack frame in the issue report. Should be better in 3.1.0pre-release4. Good catch!

**Comment by LisaAlmarode** [comment]
Not fixed in PR4.  The problem is not that it's not a class method; the problem is that RowanMethodService >> runTest:inCassName: is not visible to DataCurator.  Some handy trick lets you see the method source in the debugger when you select that frame, but not to open a browser on it.

**Comment by ericwinger** [comment]
This is going to have to wait until post-3.1.0. What is being asked is to be able to browse any code even if it's not in the user's symbol lists. While that likely can be done, it's a pretty big job because one would want to support all the `Browse`* menu options in the debugger without having a fully functional browser to do it. Not sure what that would look like. 

What I can do in the meantime is disable the `Browse`* options in the debugger if the frame's method isn't visible to the user. I'll open a new issue for 3.1.0 for that and reference this issue.

**Comment by LisaAlmarode** [comment]
I agree with deferring making this work correctly, I think that is outside the scope of this bug, I just don't like error dialogs.   I think we need a separate bug for the future work.

As for this bug:  If I double click on one of these lower methods in the list of frames, I do still get an error.  It would be nice to close this hole. 

![image](https://user-images.githubusercontent.com/13142166/79809554-9f6d7200-8325-11ea-8ec0-52d4b4310808.png)

**Comment by LisaAlmarode** [comment]
The bug I filed was hijacked, so this can go back to never-never land

**Comment by LisaAlmarode** [comment]
Running as DataCurator, the browse method menu items are disabled for methods that are not visible to me, so this can be called fixed.
