### ISSUE TITLE
Implement keyboard shortcut for 'commit' and 'abort' actions

### ISSUE THREAD

**Issue by kurtkilpela** [ericwinger/Jade#779]
Currently, a keyboard shortcut does not exist for the 'commit' and 'abort' actions. These actions require use of the mouse to select the toolbar button or the menu item in the 'Jadeite' menu.

I'd suggest the follow keyboard shortcuts are introduced to allow 'commit' and 'abort' without the use of a mouse.

commit: ctrl + shift + c
abort: ctrl + shift + a

**Comment by ericwinger** [comment]
Should have a fix in 3.1.0. 

Used Ctrl-Alt-C / A because Ctrl-Shift-A was already taken by SUnit.

**Comment by LisaAlmarode** [comment]
I don't think I can test this to where I would feel like I trusted it... there's no feedback and no way to know if you really committed or not (other than to have made a visible change and abort afterwards)... which makes it problematic to blanket test the many panes in various different browsers to be sure all of them correctly understand that shortcut.  E.g. what happens in the Sunit browser... no jadeite menu, but there are abort/commit icons... what about the debugger?  Is it universally available or only in certain places... you just don't know.  

I can say that the shortcut is missing at least from the Console, PB, and MB Jadeite menus.

Reopening since I think some way to double check on commit is needed before we can call this a completed feature (although people that don't feel strongly about commit certainly could still use the shortcuts and hope for the best).

**Comment by LisaAlmarode** [comment]
I'm also thinking that I'm not too sure I like like having control-shift-a do an abort at all; I'd prefer to at least be able to disable this feature.  I don't use shortcuts a whole lot, but since there are so many shortcuts infesting my computer, I do sometimes do things I did not intend at all to do, by accidentally using shortcuts I was unaware of.  Having to press both control and alt is better than just a control or shift, but I still feel uncomfortable with this risk.  

It will push me to use autocommit more, at least...

**Comment by ericwinger** [comment]
Maybe @kurtkilpela would like to get the latest pre-release and see if it's to his satisfaction?

**Comment by kurtkilpela** [comment]
The request is based upon the desire to be able to easily commit from the keyboard. Pressing ctrl + alt + c/a makes this harder as it still requires two hands. Technically, I can do it from one hand but it is very awkward. shift + alt +c/a does not work either. Windows binds shift + alt to changing the language. How often does Jadeite 'AutoCommit' if active?

**Comment by kurtkilpela** [comment]
If a commit happens after every change to the model, my case would be satisfied.

**Comment by kurtkilpela** [comment]
Regardless, I downloaded 3.1.0 pre-release 6 and I don't see the shortcut associated with any of the menu options in any of the Jadeite windows I use. (Console, Projects Browser, SUnit). Do I need to use some branch instead of the published pre-release?

**Comment by ericwinger** [comment]
@kurtkilpela It's not a menu option yet but it's bound to every window. With luck, you can press ctrl-alt-a/c from anywhere and commit or abort. 

AutoCommit commits on every trip to the server. Pretty much every time the user clicks on something (but not typing in a method).

**Comment by dalehenrich** [comment]
@kurtkilpela, technically I think that autocommit may commit too often, however in practical terms, commits with no dirty objects are pretty cheap (in a single user stone), I've been using autocommit since it was implemented and I don't have any complaints ...

**Comment by ericwinger** [comment]
@LisaAlmarode  @kurtkilpela Can you coordinate on what is needed? I can revert the feature. As far as the command-key combination, I don't find ctrl-alt-c/a that much different than ctrl-shift-c/a.   Regardless, I'd like to fix this and cut a pre-release 7 soon.

**Comment by kurtkilpela** [comment]
@LisaAlmarode I'm happy to just use AutoCommit and have this change reverted. Assuming you are fine with this.

**Comment by LisaAlmarode** [comment]
I suggest revert until we have time to figure it out...

**Comment by LisaAlmarode** [comment]
I'm closing this since the requestor didn't feel strongly.  Can reopen or create a new bug if it's actually needed.
