### ISSUE TITLE
(3.1.0) Wondering what purpose the `Test Execution Class` column serves in SUnit Browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#799]
I have yet to see an entry in that column deviate from the selected test class in the `Classes` column:
![image](https://user-images.githubusercontent.com/623951/80734369-e8f75300-8ac3-11ea-9e8d-85bdfdca9055.png)
I bring this up because you have to notice that by default the test pane is too narrow for me to see the full method name for tests, so I invariably spend more time resizing the panes ... and this was happening in 3.0.93, so in 3.1.0, there is even less real estate for method names, and the way the columns are implemented I have to resize both sides of the test column  to be able to see the method names

**Comment by LisaAlmarode** [comment]
It's important if you select multiple classes in the middle pane, so you know which test selector is for which class.

**Comment by LisaAlmarode** [comment]
But the default column sizes aren't ideal in the sunit browser I'd think... I have the same column issue with the console.

**Comment by ericwinger** [comment]
The `Test Execution Class` column is part of the fix for #755 and #756 which was a complaint about how the SUnit browser handles hierarchies of test classes and equivalent test selectors. 

If you'd like more screen real estate or column header name changes please coordinate with @LisaAlmarode and outline the requested changes in this issue. If you would both like behavior changes, please open a new issue. 

(Edit - And, like @LisaAlmarode mentioned, the same test selector in multiple classes caused issues, as well.)

**Comment by dalehenrich** [comment]
@LisaAlmarode, screen real estate is an issue, so I will do a little bit brainstorming ...
1. include class names as part of the test selector when multi-selection is done
2. only enable the test execution class column when multiple test classes are selected
3. make collapsing the test execution class column easier
4. preference for enable/disable the test execution class column

**Comment by LisaAlmarode** [comment]
I looked over the related issues, and my own experiences with a complicated hierarchy... and I think option 2 is a good solution. 

There were a number of complaints (many by me) around hierarchies of tests and getting the wrong results marked depend on who implemented the selector, which I'm happy to say are fixed now... but as long as the underlying code is keeping track of the execution class, I don't think the display of the execution class is helpful, since it should always be the class you see selected. The only time you need to display the class is if there is come confusion, i.e. multiple classes selected.

**Comment by LisaAlmarode** [comment]
Candidate for 3.1.1 work.

**Comment by ericwinger** [comment]
Should be fixed in the next release of Jadeite. Per option #2 [here](https://github.com/GemTalk/Jadeite/issues/799#issuecomment-622010094), the Test Execution Class only appears if you have multiple classes selected.

**Comment by LisaAlmarode** [comment]
I seem to remember problems with inherited tests, but I can't find whatever issue that was.  Test execution looks okay in trivial tests, behavior is in accordance with the original bugs (from Martin).
