### ISSUE TITLE
(3.1.0) hung debugger with unknown error trying to trim stack

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#819]
I am getting to the point, where I not able to use Jadeite for development. I need to be able to work for more that 10 minutes in a row, before having to kill my image and get back to what I am trying to figure out:
![image](https://user-images.githubusercontent.com/623951/84535710-2cd39f80-aca1-11ea-9d4c-fd5ac2049035.png)

**Comment by ericwinger** [comment]
Was able to get a recurrence of the trim stack error: 
![image](https://user-images.githubusercontent.com/36212516/86295025-919c5e80-bbaa-11ea-8e68-83e61fa28a1c.png)

1. I had put a breakpoint in the following code at the `with:` before running the method. 
2. Executed `RowanSample1 new arbitraryCode` and a debugger opened.
3. Then from inside the debugger I added a breakpoint at `show:` 
4. Then ran to `show` and tried the menu item `Restart`

![image](https://user-images.githubusercontent.com/36212516/86295141-cb6d6500-bbaa-11ea-876f-02a8578e5376.png)

**Comment by ericwinger** [comment]
This took a long time to fix and may not be complete. The heart of the problem was that Jadeite was not able to open two debuggers at once safely. 

Code inherited from early Jade development opens a debugger on a server error then sends `answer` which waits on the idleProcess to know when it may close itself or resume. See `JadeiteDebugger class>>openOn:message:terminateOnClose:` and `JadeDebugger>>answer`. It waits by sending `loopWhile:` to the current instance of `InputState` which pumps windows host messages. I believe it was done this way to allow tests to know when the debugger is ready by hooking into the `onIdleEntered` event. See `JadeiteDebugger>>initializeIdleProcess`. 

This seems to work fine when only one debugger is open.  However, if a second debugger is opened, it enters the same code path. When the second debugger sends the `loopWhile:` message, the Main thread in Dolphin is abruptly terminated and a new Main thread is opened to wait on the idle process. (I'm not quite sure how the main thread is terminated. Maybe in the Dolphin vm.) Because the original debugger's thread has been terminated, this leaves the system in a vulnerable state and many bad things can happen including stuck gui's, threads that seem to continue on the wrong stack, etc (at least that's what appears to happen). In short, weird things happen. 

After much head-scratching, the fix was to not wait for the debugger's answer on the Main thread but instead to fork off the Main thread and wait(`loopWhile:`) in a forked thread which was held onto by the debugger. Then, immediately after forking off the main process, the Main thread was suspended. Both the forked thread and the waiting thread are held by the debugger and are not the new Main thread. The Dolphin vm then spawns a new Main thread to hand gui stuff. When the forked process gets it's answer or the loop is completed, we finish the forked loop by either 1) terminating the original main thread if we're not resuming and returning or 2) reinstating the suspended main thread as the main thread and resuming while terminating the new Main thread). 

It's all horribly confusing but it not only seems to fix the problem but seems to have eliminated a number of odd gui problems I've seen in Dolphin. With luck, this will also help out some of the frustrations expressed in this issue. Yet, I'm not entirely confident this completely fixes the problem, or is the best fix. 

No particular fix version, but sha `fa7ab963` on the OscarV2.0 branch has all the changes necessary, so far, to fix the problem.

**Comment by dalehenrich** [comment]
I got hit by the two debugger problem earlier today, so I'm glad you're making progress on the hung Dolphin front ...

**Comment by LisaAlmarode** [comment]
I think that there was a fix made, and the dolphin upgrade introduced additional improvement, and later bugs filed and perhaps fixed, mean this particular bug can be closed.
