### ISSUE TITLE
(3.1.0) dialog for revert should be consistent ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#840]
This is the type of dialog that I **expect** for a `revert` menu item ... this comes up when you use the `File>>revert` menu item:
![image](https://user-images.githubusercontent.com/623951/92528062-fee8f300-f1dc-11ea-8c8b-959b1a32e253.png)
This is the `unsaved changes` dialog that you get with `Edit>>revert` menu item and is couter-intuitive, because in order to complete the operation I explicitly asked for, I have to use the `No` button, since `Yes` is the default:
![image](https://user-images.githubusercontent.com/623951/92525677-21790d00-f1d9-11ea-8cc8-d2ac54652039.png)

**Comment by LisaAlmarode** [comment]
The file > revert menu item and code pane > revert menu items both now say "You have unsaved changes: continue editing?", and the default is yes.  Same dialog on closing the window, selecting a different method.  The error is now understandable, and I think the default of keep changes is safer since an inadvertent enter would mean losing work.  I'm closing this as not or no longer a problem.
