### ISSUE TITLE
(reverted) should be more obvious in changes browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#851]
In the following image, the first entry has been reverted, but since the Selector field is clipped you can't tell difference between a reverted method and a method that just has a long selector ... 
![image](https://user-images.githubusercontent.com/623951/104665277-d048c080-5685-11eb-801b-0708b633fbce.png)

**Comment by LisaAlmarode** [comment]
Yes, this is a problem - looks exactly the same.

**Comment by ericwinger** [comment]
@LisaAlmarode @dalehenrich Is it even helpful to retain the reverted item in the list? One way to fix this is to remove it. Thoughts?

**Comment by LisaAlmarode** [comment]
Offhand, I think you need a record of what you just did since it could be a big deal if you revert the wrong thing.  Also revert needs an undo/un-revert option since after revert all changes are apparently lost.  Also while changes in the changes browser apply to the project browser immediately, if you re-make a change in the project browser the changes browser does not get updated.

**Comment by ericwinger** [comment]
> Also revert needs an undo/un-revert option since after revert all changes are apparently lost. Also while changes in the changes browser apply to the project browser immediately, if you re-make a change in the project browser the changes browser does not get updated.

Because of this [outstanding feature request](https://github.com/GemTalk/Jadeite/issues/123), I'm reluctant to make too many changes to this Changes Browser. I would invite a feature list be added to issue #123, though. If RwModifications are ready, and we're in perilous need of an upgraded changes browser, this could be prioritized. 

> Offhand, I think you need a record of what you just did since it could be a big deal if you revert the wrong thing

Good point.  What about something like this? 
![image](https://user-images.githubusercontent.com/36212516/197617388-7a171ffe-0512-4309-ad5d-4b61ea94190c.png)

**Comment by ericwinger** [comment]
Changes shown below. Reverted moved to first column and red shown. 
![image](https://user-images.githubusercontent.com/36212516/197628890-9c9da2a2-a31a-48e3-836f-8b46c861cfff.png)
