### ISSUE TITLE
Need 3.6.2 support for Jadeite

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#859]
Probably should make Oscar3.1.1pre-release2

**Comment by dalehenrich** [comment]
If it wasn't too difficult, would it make sense to replace the version dropdown with a version field that can be filled in by users ... then it might not be required to  make a jadeite release to coincide with every gemstone release  ... i suppose this probably would make sense to go along with clientlibs support, since the user would download a new clientlib (or internal dev create new directory in clientlibs and copy libs there manually) and not need to rely on a jadeite release to provide the new libs ... just thinking out loud :)

**Comment by ericwinger** [comment]
https://github.com/GemTalk/Jadeite/releases/tag/Oscar-3.1.1-pre-release2
