### ISSUE TITLE
(Oscar 3.1.0 and 3.1.1) Under certain conditions selected methods browser loses method source and errors out

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#863]
This has been a bug that I have seen for a long time, but only today did I notice that pattern that would reproduce the problem ...

1. Select one or more methods in Project Browser and open a Selected Method Browser:
   
![image](https://user-images.githubusercontent.com/623951/116944297-0fe1eb00-ac2a-11eb-80ea-41a923d28a51.png)

2. select project browser and add a new tab:

![image](https://user-images.githubusercontent.com/623951/116944417-533c5980-ac2a-11eb-9f5e-0274e38c59ae.png)

3. return to Selected Method Browser and select a different method ... kaboom:

![image](https://user-images.githubusercontent.com/623951/116944562-9696c800-ac2a-11eb-9da5-514e36248ea3.png)

4. The error is persistent until you do an implementers in SelectedMethod browser and magically the state is restored 

![image](https://user-images.githubusercontent.com/623951/116944705-db226380-ac2a-11eb-93f4-7e48fe1b0eda.png)

5. And you can close the implementors window ..

**Comment by dalehenrich** [comment]
I don't think that multiple selection is required to reproduce the problem, since I've seen this happen plenty of times without multiple selection ... but until now I didn't notice the pattern ...

**Comment by ericwinger** [comment]
The problem can be reproduced if you have a method selected in a method list browser and open a class browser on that method's class.  That sends #fastRefresh which is an optimized class refresh method in the class service. To save transport time, #fastRefresh doesn't send back method sources but that source is used in the method list browser to update the method.  The replication code didn't account for nil sources well. 

Fixed in Jadeite for Rowan 3.0. (Jadeite Oscar 3.1.1, I believe)

**Comment by LisaAlmarode** [comment]
I think this is meant to be fixed in 3.2.9 with Rowan v3 and I don't reproduce it there.
