### ISSUE TITLE
would it make sense to (or can you) specify more than one package to open project browser on during startup

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#865]
I have to go through the (tedious) ritual of opening the N packages/classes that make up my current working set every time I login and **I think that it might be useful**  to specify this in the preferences file ... when components appear< i would likely extend this request to be able to open multiple tabs on a set of component/package/class combos ... 

With that said, it also would be convenient if I could save current browser "configuration" (component/package/class combo and set of tabs) that would be a) used when I logged in and b) something that I could open after login, if I happen to have closed the project browser ...

With THAT said, perhaps we should have a brainstorming session about this?

**Comment by LisaAlmarode** [comment]
As of 3.2.11, if I have multiple lines in the preferences file, it will open multiple project browsers, e.g.
  openBrowserOnPackage: Rowan-Core
  openBrowserOnPackage: FileSystem-Core
So the central issue is fixed.

I am not sure what opening a browser on a component means... this might be package group.  I don't think it's currently supported to open a project browser on a page group from preferences.  However, I think the specific example above, you'd use openBrowserOnClass:, and that would bring the package and package group along.  So I'm going to consider this not something that needs word (unless there's clarification). 

Having preferences open multiple tabs in a project browser, rather than multiple browsers, would certainly be useful. The only API I can imagine being tolerable is making the preferences file take a list, rather than just the class name. 
This is the remaining work that is open under this issue; it's a nice-to-have, but not required for 2022. 

Trying to save the full set of open browsers so they can be reopened is big, and should wait til after we do the linux port... needs to be in a separate issue.

**Comment by dalehenrich** [comment]
Will revisit this when I've had some experience with package groups ...

**Comment by ericwinger** [comment]
The prefs file now can take a list of classes which opens in a single browser. 
> #openBrowserOnClasses: <className1 className2 ...>

There is also a save option in the Jadeite menu to write the above preference line in the preferences file. Any open tabs with a class selected is saved. 
![image](https://user-images.githubusercontent.com/36212516/197602708-3b26e1df-bbae-40ec-8b8c-af11686efbcd.png)

**Comment by LisaAlmarode** [comment]
Save Class Tabs to Preferences File is disabled in the runtime; please check packaging.  It looks like you might need to be careful about raging featuritis; this did not really deserve a menu item.  You are disallowed from adding new menu items for two weeks. 

Otherwise, setting the menu item manually does cause the appropriate browser to open.  For all four open options, you can specify more than one statement to get more than one browser open if you really want to see 8 or more project browsers opened.  However you cannot specify a list in ..OnProject, ...OnParckave, or openSUnit....  Which is not a problem, just an observation.

**Comment by ericwinger** [comment]
> Save Class Tabs to Preferences File is disabled in the runtime; please check packaging.

Added to 'must not strip' category. Rebuilt and verified menu item enabled in runtime. 

> It looks like you might need to be careful about raging featuritis; this did not really deserve a menu item. You are disallowed from adding new menu items for two weeks.

I've added a menu item to prevent me from adding menu items for two weeks. 

> However you cannot specify a list in ..OnProject, ...OnParckave, or openSUnit.... Which is not a problem, just an observation.

Unless I hear a stronger voice advocating for the ability to open tabs with only a package or project open, I think being able to open with multiple classes and save them is probably good enough.

**Comment by LisaAlmarode** [comment]
This is okay, though not perfect.  Still I'm not reopening it.
 
- I spelled a class name wrong and didn't notice, and I was baffled by the "Projects" tab, but I see that's an unselected PB. Any adjustments would have rather marginal value.
- Specifying two PackageNames means you get zero browsers, while it could have been kind enough to put up one for the first package name
- The comment on legal values doesn't apply to the class names.  But it is not very hard to try and see what happens.  Still, it does make one wonder if you can put two packages for openBrowserOnPackage:, which you can't.
