### ISSUE TITLE
After project write, menu option git commit is disabled

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#874]
This is in Oscar-3.0.91.1-prerelease2. 

If I've done a write, my changes are written to disk, but not committed to git.  But after a write, the commit to git button is disabled. So I can't commit to git until I make more changes. 

This is probably related to the attempt to make it harder to encounter bug #317.  

Minor.

**Comment by ericwinger** [comment]
I don't see any Rowan api's available that can identify a project that has uncommitted changes on disk and in the image. 

One possible way to fix this issue in Jadeite without Rowan changes would be to 
- Never disable the `Commit to Git ...` project menu option
- Wrap the menu item's action in an error handler so a dialog could be raised instead of a walkback. 

This doesn't seem like a great solution, though.  It would be better to have a Rowan api that identified uncommitted changes in a project either on disk or in the image. 

Thoughts, @LisaAlmarode ?

**Comment by LisaAlmarode** [comment]
Presumably as part of some other changes, after doing a write now, I get the tell-tale asterisk, the commit to git option is not disabled, and I can commit.
