### ISSUE TITLE
Placeholder for inability to use client GsFiles from Jadeite to 3.6.1

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#875]
Per bugs 49623 and 49007, the server has been changed between 3.2.15 and 3.6.1 such that some kinds of GCI calls cause client user actions, including GsFile operations, to be disabled.  The flags GCI_PERFORM_FLAG_ENABLE_DEBUG and  GCI_PERFORM_noClientUseraction  and GciNb... calls are implicated.

With these server changes, in Jadeite for 3.6.1, if you attempt to execute GsFile openWrite:, it results in a GciTransportError occurred (error 2728), client user action not supported during non-blocking GCI call actionNameOop 4202241.

This may not be an issue for customers... however I'm not going to be able to do any real actual work on any projects or port tools, unless this can be fixed.

**Comment by ericwinger** [comment]
Per side discussions, this should be fixed, if possible, in Jadeite that supports later versions of Rowan - probably v3.

**Comment by ericwinger** [comment]
I believe this was fixed in the latest, unreleased Jadeite that supports Rowan V3.0. It was done quite some time ago but the nb perform and execute variants Jadeite uses appear to be updated with the proper dbg & flag per issue report. 

Simple workspace tests confirm that `GsFile>>openRead:` and `GsFile>>openWrite:` work as desired now.  

Assigning to Lisa for more thorough testing when Jadeite for Rowan 3.0 is released.

**Comment by ericwinger** [comment]
Lisa verified fix. Also see https://github.com/GemTalk/Jadeite/issues/893
