### ISSUE TITLE
class hierarchy not quite right

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#891]
In Jadeite for Rowan v3.0, there are a few circumstances where the class hierarchy isn't right. All involve a newly added subclass. 

- [x] If two class hierarchies are opened on the same class and a subclass is added to one hierarchy, the new class appears in the other hierarchy correctly, but it is not in alphabetical order. 
- [x] Aborting a newly added subclass in a hierarchy doesn't get rid of it. 
- [x] Reloading a newly added subclass in a hierarchy doesn't get rid of it.

**Comment by LisaAlmarode** [comment]
The incorrect alphabetization in other browser is in 3.2.12. 
In the browser in which you added the new class, it reverted the expand hierarchy to only show the newly created subclass.  This was quite annoying (which could be since I was testing), but would mask if it was in the wrong order in the same browser too.

**Comment by ericwinger** [comment]
Finally finally finally found where to make the children of a tree  node appear in sorted order. Buried very deep in the hierarchy gui code.
