### ISSUE TITLE
[3.2.9] Package remove needed now that we have Package add

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#930]
Now that we can add packages, we need a way to remove them... since people make mistakes (not me, obviously, but someone could).

There is a package unload option that has existed but never been implemented.

**Comment by ericwinger** [comment]
Renamed Unload Package and added functionality.

**Comment by dalehenrich** [comment]
Out of curiosity, how was unload package implemented?

**Comment by ericwinger** [comment]
Probably easiest to see the checkin. Seems to work. 
https://github.com/GemTalk/RowanClientServices/commit/c181348be5081c72d9af824667e54d0a17b3375f

**Comment by dalehenrich** [comment]
Okay ... you realize that that message removes the package from the project (i.e., the package is no longer in the original component) and if you save the project to disk it will never be loaded again ... unless you add it back to the original component ...

I'm uncomfortable with implementing this feature this way... I would be more  comfortable if package adds and removes were done in the context of the component editor so that it would be very clear that component manipulation is going on here ... so have add/remove package bringing up the appropriate component editor, would be my choice :) 

However, if you and @LisaAlmarode think that this is the right way to do things, then I will quietly walk away and keep my peace :smile:

**Comment by ericwinger** [comment]
@LisaAlmarode - thoughts?
