### ISSUE TITLE
(3.2.10) need to be able to specify an http url in 'Load project spec' dialog ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#939]
I've recently updated Rowan v3 to take an https:// or a file:// url when specify the url for a load spec, however if I enter an https: url for a load spec (https://raw.githubusercontent.com/dalehenrich/RowanSample9/master/specs/spec_0006.ston) I get a FileDoesNotExistException (see attached stack).

To differentiate, we _could_ require a file url (use 'xxx' asRwUrl) to determine if a file: or https: scheme is being used ...

[stack.txt](https://github.com/GemTalk/Jadeite/files/9456928/stack.txt)

**Comment by ericwinger** [comment]
Currently, Jadeite prepends 'file:' in front of the Path entered before the server receives the install command from the dialog. However, we could add two radio buttons in the lower left of the Load Project Spec gui - *file *url.  If *url is selected, the Path would be taken as-is and prepended with: 'https'. Otherwise, if *file is selected, the path would be constructed like it is now. Then, the `asUrl` call would do the right thing on the server. 

Thoughts? @LisaAlmarode @dalehenrich 

![image](https://user-images.githubusercontent.com/36212516/194956111-8525a04a-6399-42ed-a435-5fd8119bf7cd.png)

**Comment by LisaAlmarode** [comment]
For the record, I'm in favor of radio buttons.  Probably default to file and then turn it to file if the users has activity in the file selection areas.

**Comment by ericwinger** [comment]
There's a new URL tab on the load project dialog from which the user can copy/paste a url to load.
