### ISSUE TITLE
[3.2.12] Ability to disable unused-method-temp compiler warnings during load/filein

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#957]
On filein, as as I recall on project load, every method that has unused method temps puts up a dialog that I have to click on yes to.  My historic non-jadeite code is teeming with method temps, and filein is very painful. I just pressed enter continuously until it was over.

I think on filein or load you should never have to see compiler warning dialogs for unused method temps; watcha gonna do, and they create no particular harm.  Other kinds of compiler warnings we can discuss.

Failing that, a preference at least!

**Comment by dalehenrich** [comment]
My $0.02.

When you want CompileWarnings, you want all warnings ... so I'm inclined to have have a Warnings preference ... on second thought, I never want to see 'not optimized' warnings, because there's nothing you can do to to fix the Warning ... on third thought when you want CompilerWarnings, you want them all ... on fourth thought (quietly) writing Warnings to the Transcript is probably a better way to go ... if someone asks for Warnings, we an tell them that they are written to Transcript and we're done ...

End $0.02.

**Comment by ericwinger** [comment]
[3.2.13] I've disabled CompileWarning's on file in. If we want a preference instead, let's open a new issue with specifics.

**Comment by LisaAlmarode** [comment]
They are still causing me great suffering on project load. Please make these go away.

Confirmed that filein doesn't put up warnings, but it doesn't write anything to the transcript either.  Was it supposed to?  It would be handy - I don't mind fixing the problems but I don't know how I'd figure them out.

**Comment by ericwinger** [comment]
Found another path that needed to suppress warnings. Testing manually against Lisa's AAA project showed successful suppression.
