### ISSUE TITLE
Icon coordination needed

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#965]
The runtime & development environment sometimes have different icons. Should coordinate them sometime. Need Lisa's input.

**Comment by LisaAlmarode** [comment]
I think we have decided that icons are not needed in the project lists.  I suggest they are not needed for packages either.  I think that removing these icons would make this bug a non-issue, assuming the meaning of this bug was specific to project icons and not icon bars and debugger and so on. Make it target so Eric can confirm this and close when icons are removed.

**Comment by ericwinger** [comment]
I removed the icons from the package list. Project list icons are already gone. Should remove any other list icons if they are discovered.
